/**
 * Chorale Realization Engine
 * ─────────────────────────
 * Pure engine — zero React/UI dependencies.
 * Input:  RomanChord[] + tonic + mode + time signature + rules config
 * Output: StaffNote[] identical to GrandStaffEditor format
 *
 * Responsibilities:
 *   - Parse roman numerals → chord tones (spelling-first, diatonic)
 *   - Realize SATB voicings respecting voice ranges
 *   - Voice leading: smallest motion, contrary/oblique preferred
 *   - Rule checking: no parallel 5ths/8ves, voice crossing, spacing, doubling
 *   - Resolution: leading tone → tonic, 7ths resolve down by step
 *
 * Testable with plain `npx tsx` + unit tests (no DOM, no Electron).
 */

import type { StaffNote, Voice, TimeSignature, KeySignature } from '../types';
import { TICKS_PER_QUARTER, DURATION_VALUES } from '../constants';

// ─── Types ─────────────────────────────────────────────────────────────────

/** Roman numeral chord descriptor (engine input). */
export type RomanChord = {
  /** Roman numeral string, e.g. 'I', 'ii', 'V7', 'viio', 'IV6', 'V65' */
  roman: string;
  /** Inversion (0 = root, 1 = first, 2 = second, 3 = third for 7ths) */
  inversion?: number;
  /** Beat within the measure (1-based, can be fractional) */
  beat: number;
  /** Measure index (0-based) */
  measure: number;
  /** Explicit note duration (e.g. 'whole', 'half', 'quarter', 'eighth'). If omitted, auto-calculated. */
  duration?: string;
  /**
   * Modulation: override tonic from this chord onwards.
   * e.g. 'G' for G major, 'g' for G minor.
   * Upper-case letter = major, lower-case letter = minor.
   * Accidentals follow: 'Bb' = Bb major, 'f#' = F# minor.
   */
  modulateTo?: string;
};

/** User-configurable rules for the realization engine. */
export type ChoralRules = {
  /** Allow parallel 5ths (default: false → forbidden) */
  allowParallel5ths?: boolean;
  /** Allow parallel 8ves (default: false → forbidden) */
  allowParallel8ves?: boolean;
  /** Allow voice crossing (default: false → forbidden) */
  allowCrossing?: boolean;
  /** Allow voice overlap (default: false → forbidden) */
  allowOverlap?: boolean;
  /** Always double the root in root-position triads (default: true) */
  doubleRoot?: boolean;
};

/** Configuration for the realization engine. */
export type ChoralConfig = {
  tonic: string;          // e.g. 'C', 'Bb', 'F#'
  isMinor: boolean;
  timeSignature: TimeSignature;
  rules?: ChoralRules;
  /**
   * Optional soprano melody constraint.
   * When provided, the soprano voice is fixed to these MIDI values
   * and only A/T/B are generated by the engine.
   * Each entry maps to a chord in the progression by (measure, beat).
   */
  sopranoMelody?: SopranoConstraint[];
  /**
   * Optional bass melody constraint ("basso dato").
   * When provided, the bass voice is fixed to these MIDI values
   * and only S/A/T are generated by the engine.
   */
  bassMelody?: SopranoConstraint[];
  /**
   * Optional locked voices constraint.
   * Keys are voice numbers (1=S, 2=A, 3=T, 4=B).
   * Values are arrays of { midi, measure, beat } similar to SopranoConstraint.
   * When provided, the engine fixes those voices and only generates the unlocked ones.
   * Note: if sopranoMelody is also provided, voice 1 is already handled by that.
   */
  lockedVoices?: Record<number, SopranoConstraint[]>;
  /** When false, the engine will never add automatic sevenths (only explicit V7/viio7 etc.).
   *  Defaults to true. */
  autoSevenths?: boolean;
  /** Initial chord voicing disposition (bottom to top: Bass=Root, then Tenor, Alto, Soprano).
   * Digits: 8=Root(octave), 3=3rd, 5=5th. e.g. 'R358' = B=Root, T=3rd, A=5th, S=8va.
   * 'auto' (default) = engine picks best voicing. Only effective for first chord in root position. */
  initialDisposition?: 'auto' | 'R358' | 'R538' | 'R835' | 'R385' | 'R583' | 'R853';
};

/** A single soprano constraint point (one note of the given melody). */
export type SopranoConstraint = {
  midi: number;
  measure: number;
  beat: number;
};

/** A single SATB voicing (MIDI values). */
export type SATBVoicing = {
  soprano: number;  // MIDI
  alto: number;
  tenor: number;
  bass: number;
};

/** Violation found during realization. */
export type ChoralViolation = {
  type: 'parallel-5th' | 'parallel-8ve' | 'voice-crossing' | 'voice-overlap'
      | 'spacing' | 'range' | 'doubling' | 'resolution';
  description: string;
  measure: number;
  beat: number;
  voices?: string[];
};

/** Engine output. */
/** Context marker emitted when the composer modulates to a new key. */
export type ModulationContext = {
  /** Absolute beat position (quarter-note beats from start). */
  absBeat: number;
  measureIndex: number;
  beat: number;
  newTonic: string;
  newIsMinor: boolean;
  label?: string;
  source: 'composer';
};

export type ChoralRealizationResult = {
  notes: StaffNote[];
  violations: ChoralViolation[];
  /** Modulation contexts for the analysis engine. */
  modulationContexts: ModulationContext[];
};

// ─── Constants ─────────────────────────────────────────────────────────────

/** SATB voice ranges (MIDI), generous but standard for chorale writing. */
const VOICE_RANGES: Record<string, { min: number; max: number }> = {
  soprano: { min: 60, max: 79 },  // C4 – G5
  alto:    { min: 55, max: 74 },  // G3 – D5
  tenor:   { min: 48, max: 67 },  // C3 – G4
  bass:    { min: 40, max: 60 },  // E2 – C4
};

/** Diatonic pitch classes (letter only) */
const DIATONIC = ['C', 'D', 'E', 'F', 'G', 'A', 'B'] as const;

/** Semitone offsets for each diatonic letter from C. */
const LETTER_TO_SEMI: Record<string, number> = {
  C: 0, D: 2, E: 4, F: 5, G: 7, A: 9, B: 11,
};

/**
 * Major scale intervals in semitones from root.
 * Index = scale degree (0-based: 0=tonic, 1=supertonic, …, 6=leading tone).
 */
const MAJOR_SCALE_SEMITONES = [0, 2, 4, 5, 7, 9, 11];

/**
 * Natural minor scale intervals in semitones from root.
 */
const NATURAL_MINOR_SCALE_SEMITONES = [0, 2, 3, 5, 7, 8, 10];

/**
 * Harmonic minor scale intervals — raised 7th.
 */
const HARMONIC_MINOR_SCALE_SEMITONES = [0, 2, 3, 5, 7, 8, 11];

// ─── Pitch Utilities ───────────────────────────────────────────────────────

/** Pitch-class (0-11) from a note name string (e.g. 'Bb' → 10, 'F#' → 6). */
function noteNameToPc(name: string): number {
  const letter = name.charAt(0).toUpperCase();
  let pc = LETTER_TO_SEMI[letter] ?? 0;
  for (let i = 1; i < name.length; i++) {
    if (name[i] === '#') pc++;
    else if (name[i] === 'b') pc--;
  }
  return ((pc % 12) + 12) % 12;
}

/** Letter index (0=C … 6=B) for a given letter. */
function letterIndex(letter: string): number {
  return DIATONIC.indexOf(letter.charAt(0).toUpperCase() as typeof DIATONIC[number]);
}

/** Diatonic position (0=C4, 1=D4, etc.) for a pitch letter + octave. */
function notePosition(pitch: string, octave: number): number {
  const li = letterIndex(pitch);
  return li + (octave - 4) * 7;
}

/** MIDI value for a given pitch letter, accidental string, and octave. */
function pitchToMidi(letter: string, accidentalStr: string, octave: number): number {
  let semi = LETTER_TO_SEMI[letter.toUpperCase()] ?? 0;
  for (const ch of accidentalStr) {
    if (ch === '#') semi++;
    else if (ch === 'b') semi--;
  }
  return (octave + 1) * 12 + ((semi % 12) + 12) % 12;
}

/** Chromatic pitch class (noteIndex) from MIDI. */
function midiToNoteIndex(midi: number): number {
  return ((midi % 12) + 12) % 12;
}

// ─── Scale & Key Helpers ───────────────────────────────────────────────────

export type ScaleDegreeNote = {
  letter: string;       // e.g. 'B', 'E'
  accidental: string;   // e.g. '', '#', 'b', 'bb'
  semiFromRoot: number; // semitones above tonic
  degree: number;       // 0-based scale degree
};

/**
 * Build the 7 diatonic scale notes for a given tonic + mode.
 * Returns letter + accidental + semitone offset for each degree.
 *
 * Uses harmonic minor for minor keys (raised 7th on degree 6).
 */
export function buildScale(tonic: string, isMinor: boolean): ScaleDegreeNote[] {
  const tonicLetter = tonic.charAt(0).toUpperCase();
  const tonicAcc = tonic.slice(1); // '', '#', 'b'
  const tonicPc = noteNameToPc(tonic);
  const tonicLetterIndex = letterIndex(tonicLetter);

  // Choose interval template
  const template = isMinor ? HARMONIC_MINOR_SCALE_SEMITONES : MAJOR_SCALE_SEMITONES;

  const result: ScaleDegreeNote[] = [];
  for (let deg = 0; deg < 7; deg++) {
    // Diatonic letter = tonic letter + deg steps up the alphabet
    const li = (tonicLetterIndex + deg) % 7;
    const letter = DIATONIC[li];
    // Natural (un-accidentaled) semitone for this letter
    const naturalSemi = LETTER_TO_SEMI[letter];
    // Target semitone (relative to C) for this scale degree
    const targetSemi = (tonicPc + template[deg]) % 12;
    // Accidental = difference between target and natural
    let diff = targetSemi - naturalSemi;
    // Normalize to -2..+2 range
    if (diff > 6) diff -= 12;
    if (diff < -6) diff += 12;
    let accidental = '';
    if (diff > 0) accidental = '#'.repeat(diff);
    else if (diff < 0) accidental = 'b'.repeat(-diff);

    result.push({
      letter,
      accidental,
      semiFromRoot: template[deg],
      degree: deg,
    });
  }
  return result;
}

/**
 * Build the natural minor scale (without raised 7th).
 * Used for diatonic chords that don't include the leading tone.
 */
export function buildNaturalMinorScale(tonic: string): ScaleDegreeNote[] {
  const tonicLetter = tonic.charAt(0).toUpperCase();
  const tonicPc = noteNameToPc(tonic);
  const tonicLetterIndex = letterIndex(tonicLetter);
  const template = NATURAL_MINOR_SCALE_SEMITONES;
  const result: ScaleDegreeNote[] = [];
  for (let deg = 0; deg < 7; deg++) {
    const li = (tonicLetterIndex + deg) % 7;
    const letter = DIATONIC[li];
    const naturalSemi = LETTER_TO_SEMI[letter];
    const targetSemi = (tonicPc + template[deg]) % 12;
    let diff = targetSemi - naturalSemi;
    if (diff > 6) diff -= 12;
    if (diff < -6) diff += 12;
    let accidental = '';
    if (diff > 0) accidental = '#'.repeat(diff);
    else if (diff < 0) accidental = 'b'.repeat(-diff);
    result.push({ letter, accidental, semiFromRoot: template[deg], degree: deg });
  }
  return result;
}

// ─── Roman Numeral Parsing ─────────────────────────────────────────────────

/** Quality derived from roman numeral case + suffix. */
export type ChordQuality = 'major' | 'minor' | 'diminished' | 'augmented'
                         | 'dominant7' | 'major7' | 'minor7' | 'halfDim7' | 'dim7'
                         | 'aug6It' | 'aug6Fr' | 'aug6Ger';

export type ParsedRoman = {
  degree: number;         // 0-based scale degree
  quality: ChordQuality;
  inversion: number;      // 0 = root, 1 = 1st, 2 = 2nd, 3 = 3rd (7ths only)
  hasSeventh: boolean;
  /** Original text for display. */
  raw: string;
  /** Secondary target degree (0-based) for applied chords like V/V, viio/ii */
  secondaryTarget?: number;
  /** Chromatic alteration of the root: -1 = flat (bII), +1 = sharp (#IV) */
  chromaticShift?: number;
  /** Augmented sixth chord type */
  aug6Type?: 'it' | 'fr' | 'ger';
};

/**
 * Parse a roman numeral string into structured data.
 *
 * Supports: I ii III iv V vi VII (case → major/minor),
 *   '+' (augmented), 'o'/'°'/'dim' (diminished),
 *   '7' (seventh), 'ø7'/'ø' (half-diminished),
 *   figured bass inversions: 6, 64, 7, 65, 43, 42, 2,
 *   slash notation: 6/4, 6/5, 4/3, 4/2, 5/3.
 */
export function parseRoman(input: string): ParsedRoman {
  let s = input.trim();
  const raw = s;

  // ── Secondary dominant detection: V/V, viio/ii, V7/IV etc. ──
  // Must detect BEFORE figured-bass normalization, but only for roman-numeral targets
  let secondaryTarget: number | undefined;
  const secondaryMatch = s.match(/\/([IViv]+)$/);
  if (secondaryMatch) {
    const targetRoman = secondaryMatch[1];
    const romanMap2: Record<string, number> = {
      I: 0, II: 1, III: 2, IV: 3, V: 4, VI: 5, VII: 6,
      i: 0, ii: 1, iii: 2, iv: 3, v: 4, vi: 5, vii: 6,
    };
    // Try longest match
    const candidates2 = ['VII', 'III', 'vii', 'iii', 'IV', 'VI', 'II', 'iv', 'vi', 'ii', 'V', 'I', 'v', 'i'];
    for (const c of candidates2) {
      if (targetRoman === c) {
        secondaryTarget = romanMap2[c];
        s = s.slice(0, -(targetRoman.length + 1)); // remove /target
        break;
      }
    }
  }

  // Augmented sixth chords: It6, Fr6, Ger6 — must be detected BEFORE figured
  // bass extraction because FB regex would consume the trailing '6'.
  const aug6Match = s.match(/^(It|Fr|Ger)\+?6/i);
  if (aug6Match) {
    const t = aug6Match[1].charAt(0).toUpperCase() + aug6Match[1].slice(1).toLowerCase();
    return {
      degree: 5,
      quality: ('aug6' + t) as ChordQuality,
      inversion: 0,
      hasSeventh: false,
      raw,
      chromaticShift: -1,
      aug6Type: t.toLowerCase() as 'it' | 'fr' | 'ger',
      secondaryTarget,
    };
  }

  // Detect figured bass inversion suffix (must be parsed before removing digits)
  let figuredBass = '';

  // Normalize slash notation: 6/4→64, 6/5→65, 4/3→43, 4/2→42, 5/3→53
  s = s.replace(/6\/4/g, '64')
       .replace(/6\/5/g, '65')
       .replace(/4\/3/g, '43')
       .replace(/4\/2/g, '42')
       .replace(/5\/3/g, '53');

  // Check for figured bass patterns: 65, 64, 53, 43, 42, then single digits 6, 7, 2
  const fbMatch = s.match(/(65|64|53|43|42|6|7|2)$/);
  if (fbMatch) {
    figuredBass = fbMatch[1];
    s = s.slice(0, -figuredBass.length);
  }

  // Detect quality modifiers
  let qualMod: 'aug' | 'dim' | 'halfDim' | null = null;
  if (s.endsWith('+')) { qualMod = 'aug'; s = s.slice(0, -1); }
  else if (s.endsWith('°') || s.endsWith('o') || s.endsWith('dim')) {
    qualMod = 'dim';
    if (s.endsWith('dim')) s = s.slice(0, -3);
    else s = s.slice(0, -1);
  }
  else if (s.includes('ø') || s.includes('Ø')) {
    qualMod = 'halfDim';
    s = s.replace(/[øØ]/g, '');
  }

  // Chromatic prefix: b/♭ or #/♯ shifts the root (bII, bVII, #IV, etc.)
  let chromaticShift = 0;
  if (/^[b♭](?=[IViv])/.test(s)) { chromaticShift = -1; s = s.slice(1); }
  else if (/^[#♯](?=[IViv])/.test(s)) { chromaticShift = +1; s = s.slice(1); }

  // Map roman text → degree (0-based)
  const romanMap: Record<string, number> = {
    I: 0, II: 1, III: 2, IV: 3, V: 4, VI: 5, VII: 6,
    i: 0, ii: 1, iii: 2, iv: 3, v: 4, vi: 5, vii: 6,
  };

  // Try longest match first
  let degree = -1;
  let isLowerCase = false;
  const candidates = ['VII', 'III', 'vii', 'iii', 'IV', 'VI', 'II', 'iv', 'vi', 'ii', 'V', 'I', 'v', 'i'];
  for (const c of candidates) {
    if (s.startsWith(c)) {
      degree = romanMap[c];
      isLowerCase = c === c.toLowerCase();
      s = s.slice(c.length);
      break;
    }
  }
  if (degree < 0) {
    // Fallback: treat as I
    degree = 0;
    isLowerCase = false;
  }

  // Check for remaining '7' (or dom7/maj7/M7/Δ7) that wasn't part of figured bass
  let hasSeventh = false;
  let forceMaj7 = false;
  let forceDom7 = false;
  // Explicit dom7 suffix → always dominant seventh (check before maj7 and plain '7')
  if (/dom7/i.test(s)) {
    hasSeventh = true;
    forceDom7 = true;
    s = s.replace(/dom7/i, '');
  }
  // Handle case where figured bass already captured the '7' (e.g. IVdom7 → fb='7', s='dom')
  else if (/^dom$/i.test(s)) {
    forceDom7 = true;
    s = '';
  }
  // Explicit maj7/M7/Δ7 suffix → always major seventh (check before plain '7')
  else if (/maj7|M7|Δ7/.test(s)) {
    hasSeventh = true;
    forceMaj7 = true;
    s = s.replace(/maj7|M7|Δ7/, '');
  }
  // Handle case where figured bass already captured the '7' (e.g. IVmaj7 → fb='7', s='maj')
  else if (/^(maj|M|Δ)$/i.test(s)) {
    forceMaj7 = true;
    s = '';
  }
  else if (s.includes('7')) {
    hasSeventh = true;
    s = s.replace('7', '');
  }
  // Figured bass implies seventh for 7, 65, 43, 42, 2
  if (['7', '65', '43', '42', '2'].includes(figuredBass)) {
    hasSeventh = true;
  }

  // Determine quality
  let quality: ChordQuality;
  if (hasSeventh) {
    if (qualMod === 'dim') quality = 'dim7';
    else if (qualMod === 'halfDim') quality = 'halfDim7';
    else if (forceDom7) quality = 'dominant7';
    else if (forceMaj7) quality = 'major7';
    else if (isLowerCase) quality = 'minor7';
    else if (degree === 4) quality = 'dominant7';
    else quality = 'major7';
  } else {
    if (qualMod === 'aug') quality = 'augmented';
    else if (qualMod === 'dim') quality = 'diminished';
    else if (isLowerCase) quality = 'minor';
    else quality = 'major';
  }

  // Determine inversion from figured bass
  let inversion = 0;
  if (figuredBass === '6') inversion = 1;
  else if (figuredBass === '64') inversion = 2;
  else if (figuredBass === '65') inversion = 1;
  else if (figuredBass === '43') inversion = 2;
  else if (figuredBass === '42' || figuredBass === '2') inversion = 3;
  // '53' = explicit root position (no change)
  else if (figuredBass === '53') inversion = 0;
  // '7' alone = root position seventh chord
  else if (figuredBass === '7') inversion = 0;

  return { degree, quality, inversion, hasSeventh, raw, secondaryTarget, chromaticShift: chromaticShift || undefined };
}

// ─── Chord Tones from Parsed Roman ─────────────────────────────────────────

/**
 * Given a parsed roman numeral and a scale, return the chord tones
 * as pitch classes (semitones from C) + scale note info.
 *
 * Returns 3 notes (triad) or 4 notes (seventh chord), root-ordered.
 */
export function getChordTones(
  parsed: ParsedRoman,
  scale: ScaleDegreeNote[],
  tonic: string,
  isMinor: boolean
): ScaleDegreeNote[] {
  const tonicPc = noteNameToPc(tonic);
  const deg = parsed.degree;

  // ── Secondary dominant: build temporary scale from target degree ──
  if (parsed.secondaryTarget != null) {
    // Find the target note in the main scale
    const mainScale = isMinor ? buildNaturalMinorScale(tonic) : scale;
    const targetNote = mainScale[parsed.secondaryTarget];
    const targetNoteName = targetNote.letter + targetNote.accidental;
    // Build a major scale from the target note (secondary dominants are always
    // analyzed relative to a major-mode target, even in minor keys)
    const targetScale = buildScale(targetNoteName, false);
    const targetPc = noteNameToPc(targetNoteName);
    // Use getChordTones recursively without secondaryTarget
    const innerParsed: ParsedRoman = {
      ...parsed,
      secondaryTarget: undefined,
    };
    const rawTones = getChordTones(innerParsed, targetScale, targetNoteName, false);
    // Remap semiFromRoot: convert from target-relative to original-tonic-relative
    const targetOffset = ((targetPc - tonicPc) + 12) % 12;
    return rawTones.map(t => ({
      ...t,
      semiFromRoot: (t.semiFromRoot + targetOffset) % 12,
    }));
  }

  // For minor keys, use natural minor for most degrees, harmonic for V and viio
  let effectiveScale = scale;
  if (isMinor) {
    const needsHarmonic = (parsed.degree === 4 && !parsed.quality.startsWith('minor'))
                       || (parsed.degree === 6 && (parsed.quality === 'diminished' || parsed.quality === 'dim7' || parsed.quality === 'halfDim7'));
    if (!needsHarmonic) {
      // Use natural minor scale for non-dominant/non-leading-tone chords
      effectiveScale = buildNaturalMinorScale(tonic);
    }
  }

  // ── Helper: build a properly-spelled ScaleDegreeNote from absolute semitones ──
  const tonicPcLocal = noteNameToPc(tonic);
  const tonicLiLocal = letterIndex(tonic);
  /** Build a ScaleDegreeNote with correct letter/accidental spelling.
   *  @param degreeOffset  diatonic letter steps above tonic (0-6)
   *  @param semiFromRoot  semitones above tonic (0-11)
   */
  const spellNote = (degreeOffset: number, semiFromRoot: number): ScaleDegreeNote => {
    const li = (tonicLiLocal + degreeOffset) % 7;
    const letter = DIATONIC[li];
    const naturalSemi = LETTER_TO_SEMI[letter];
    const targetSemi = (tonicPcLocal + semiFromRoot) % 12;
    let diff = targetSemi - naturalSemi;
    if (diff > 6) diff -= 12;
    if (diff < -6) diff += 12;
    let accidental = '';
    if (diff > 0) accidental = '#'.repeat(diff);
    else if (diff < 0) accidental = 'b'.repeat(-diff);
    return { letter, accidental, semiFromRoot, degree: degreeOffset };
  };

  // ── Augmented sixth chords: special interval structures ──
  if (parsed.aug6Type) {
    const rootSemi = (effectiveScale[deg].semiFromRoot + (parsed.chromaticShift || 0) + 12) % 12;
    // Root on ♭6, M3 = letter+2 steps, P5/A4 = letter+4 steps, A6 = letter+5 steps (= #4)
    const tones: ScaleDegreeNote[] = [spellNote(deg, rootSemi)];
    tones.push(spellNote((deg + 2) % 7, (rootSemi + 4) % 12));   // M3
    if (parsed.aug6Type === 'fr') {
      tones.push(spellNote((deg + 3) % 7, (rootSemi + 6) % 12)); // A4 (= #2 in context)
    }
    if (parsed.aug6Type === 'ger') {
      tones.push(spellNote((deg + 4) % 7, (rootSemi + 7) % 12)); // P5
    }
    tones.push(spellNote((deg + 5) % 7, (rootSemi + 10) % 12));  // A6 (= #4 in context)
    return tones;
  }

  // ── Chromatically altered degrees (bII, bVII, #IV etc.):
  //    quality-based interval stacking with correct enharmonic spelling ──
  if (parsed.chromaticShift) {
    const rootSemi = (effectiveScale[deg].semiFromRoot + parsed.chromaticShift + 12) % 12;
    const q = parsed.quality;
    const m3 = (q === 'minor' || q === 'diminished' || q === 'minor7' || q === 'halfDim7' || q === 'dim7') ? 3 : 4;
    const p5 = (q === 'diminished' || q === 'dim7' || q === 'halfDim7') ? 6 : (q === 'augmented' ? 8 : 7);
    const chTones: ScaleDegreeNote[] = [
      spellNote(deg, rootSemi),
      spellNote((deg + 2) % 7, (rootSemi + m3) % 12),
      spellNote((deg + 4) % 7, (rootSemi + p5) % 12),
    ];
    if (parsed.hasSeventh) {
      const s7 = (q === 'dominant7' || q === 'minor7' || q === 'halfDim7') ? 10 : (q === 'dim7' ? 9 : 11);
      chTones.push(spellNote((deg + 6) % 7, (rootSemi + s7) % 12));
    }
    return chTones;
  }

  // Root, 3rd, 5th (diatonic stacking)
  const root = effectiveScale[deg];
  const third = effectiveScale[(deg + 2) % 7];
  const fifth = effectiveScale[(deg + 4) % 7];

  const tones: ScaleDegreeNote[] = [
    { ...root },
    { ...third },
    { ...fifth },
  ];

  // Adjust quality if needed (augmented 5th, diminished 5th, etc.)
  const rootPc = (tonicPc + root.semiFromRoot) % 12;
  const thirdPc = (tonicPc + third.semiFromRoot) % 12;
  const fifthPc = (tonicPc + fifth.semiFromRoot) % 12;

  const thirdInterval = ((thirdPc - rootPc) + 12) % 12;
  const fifthInterval = ((fifthPc - rootPc) + 12) % 12;

  // For augmented chords: raise the 5th by a semitone
  if (parsed.quality === 'augmented' && fifthInterval !== 8) {
    const raised = { ...tones[2] };
    raised.semiFromRoot = (raised.semiFromRoot + 1) % 12;
    // Adjust accidental
    if (raised.accidental === 'b') raised.accidental = '';
    else if (raised.accidental === '') raised.accidental = '#';
    else raised.accidental = raised.accidental + '#';
    tones[2] = raised;
  }

  // For diminished chords: the natural stacking should already produce dim 5th
  // (e.g. viio in major → B-D-F → m3 + m3 = dim5). No manual adjustment needed
  // unless the scale gives a perfect 5th unexpectedly.
  if ((parsed.quality === 'diminished' || parsed.quality === 'dim7' || parsed.quality === 'halfDim7') && fifthInterval === 7) {
    const lowered = { ...tones[2] };
    lowered.semiFromRoot = (lowered.semiFromRoot - 1 + 12) % 12;
    if (lowered.accidental === '#') lowered.accidental = '';
    else if (lowered.accidental === '') lowered.accidental = 'b';
    else lowered.accidental = lowered.accidental + 'b';
    tones[2] = lowered;
  }

  // Add seventh if needed
  if (parsed.hasSeventh) {
    const seventh = effectiveScale[(deg + 6) % 7];
    const seventhPc = (tonicPc + seventh.semiFromRoot) % 12;
    const seventhInterval = ((seventhPc - rootPc) + 12) % 12;

    const adjustedSeventh = { ...seventh };

    // dominant7 → minor 7th (10 semitones)
    if (parsed.quality === 'dominant7' && seventhInterval !== 10) {
      adjustedSeventh.semiFromRoot = (root.semiFromRoot + 10) % 12;
      // Recalculate accidental
      const targetSemi = (tonicPc + adjustedSeventh.semiFromRoot) % 12;
      const naturalSemi = LETTER_TO_SEMI[adjustedSeventh.letter];
      let diff = targetSemi - naturalSemi;
      if (diff > 6) diff -= 12;
      if (diff < -6) diff += 12;
      adjustedSeventh.accidental = diff > 0 ? '#'.repeat(diff) : diff < 0 ? 'b'.repeat(-diff) : '';
    }
    // major7 → major 7th (11 semitones)
    else if (parsed.quality === 'major7' && seventhInterval !== 11) {
      adjustedSeventh.semiFromRoot = (root.semiFromRoot + 11) % 12;
      const targetSemi = (tonicPc + adjustedSeventh.semiFromRoot) % 12;
      const naturalSemi = LETTER_TO_SEMI[adjustedSeventh.letter];
      let diff = targetSemi - naturalSemi;
      if (diff > 6) diff -= 12;
      if (diff < -6) diff += 12;
      adjustedSeventh.accidental = diff > 0 ? '#'.repeat(diff) : diff < 0 ? 'b'.repeat(-diff) : '';
    }
    // halfDim7 → minor 7th (10 semitones)
    else if (parsed.quality === 'halfDim7' && seventhInterval !== 10) {
      adjustedSeventh.semiFromRoot = (root.semiFromRoot + 10) % 12;
      const targetSemi = (tonicPc + adjustedSeventh.semiFromRoot) % 12;
      const naturalSemi = LETTER_TO_SEMI[adjustedSeventh.letter];
      let diff = targetSemi - naturalSemi;
      if (diff > 6) diff -= 12;
      if (diff < -6) diff += 12;
      adjustedSeventh.accidental = diff > 0 ? '#'.repeat(diff) : diff < 0 ? 'b'.repeat(-diff) : '';
    }
    // dim7 → diminished 7th (9 semitones)
    else if (parsed.quality === 'dim7' && seventhInterval !== 9) {
      adjustedSeventh.semiFromRoot = (root.semiFromRoot + 9) % 12;
      const targetSemi = (tonicPc + adjustedSeventh.semiFromRoot) % 12;
      const naturalSemi = LETTER_TO_SEMI[adjustedSeventh.letter];
      let diff = targetSemi - naturalSemi;
      if (diff > 6) diff -= 12;
      if (diff < -6) diff += 12;
      adjustedSeventh.accidental = diff > 0 ? '#'.repeat(diff) : diff < 0 ? 'b'.repeat(-diff) : '';
    }

    tones.push(adjustedSeventh);
  }

  return tones;
}

// ─── Voicing Realization ───────────────────────────────────────────────────

/** Pitch class (0-11) of a ScaleDegreeNote. */
function toneToMidiPc(tone: ScaleDegreeNote): number {
  return ((LETTER_TO_SEMI[tone.letter] ?? 0) +
    (tone.accidental === '#' ? 1 : tone.accidental === 'b' ? -1 :
     tone.accidental === '##' ? 2 : tone.accidental === 'bb' ? -2 : 0) + 12) % 12;
}

/** All MIDI pitches for a given chord tone within a voice range. */
function pitchesInRange(tone: ScaleDegreeNote, range: { min: number; max: number }): number[] {
  const pc = ((LETTER_TO_SEMI[tone.letter] ?? 0) + (tone.accidental === '#' ? 1 : tone.accidental === 'b' ? -1 :
    tone.accidental === '##' ? 2 : tone.accidental === 'bb' ? -2 : 0) + 12) % 12;
  const results: number[] = [];
  // Scan octaves 1-7
  for (let oct = 1; oct <= 7; oct++) {
    const midi = (oct + 1) * 12 + pc;
    if (midi >= range.min && midi <= range.max) {
      results.push(midi);
    }
  }
  return results;
}

/** Absolute distance in semitones between two MIDI notes. */
function midiDistance(a: number, b: number): number {
  return Math.abs(a - b);
}

/**
 * Realize the first chord in a progression (no prior voicing to reference).
 * Strategy: place bass note from chord tones + inversion, then fill SAT
 * with closest smooth voicing in comfortable ranges, doubling the root.
 */
export function realizeFirstChord(
  tones: ScaleDegreeNote[],
  inversion: number,
  rules: ChoralRules,
  fixedSoprano?: number,
  fixedBass?: number,
  tonicPc?: number,
  disposition?: string
): SATBVoicing | null {
  if (tones.length < 3) return null;

  // Determine bass pitch class based on inversion
  const bassToneIndex = inversion % tones.length;
  const bassTone = tones[bassToneIndex];

  // Find bass MIDI — prefer the lower end of bass range
  const bassCandidates = pitchesInRange(bassTone, VOICE_RANGES.bass);
  if (bassCandidates.length === 0) return null;
  // Choose a comfortable bass note (middle of range)
  const bassMidi = fixedBass ?? bassCandidates[Math.floor(bassCandidates.length / 2)];

  // ── Explicit disposition path ─────────────────────────────────────────
  // If a specific voicing disposition is requested (e.g. 'R358' = Bass=Root, Tenor=3rd, Alto=5th, Soprano=8va),
  // assign upper voices accordingly. Only applies in root position without fixed soprano.
  if (disposition && disposition !== 'auto' && disposition.length === 4 && inversion === 0 && fixedSoprano == null) {
    const digitToTone = (d: string): ScaleDegreeNote | null => {
      if (d === '3' && tones.length > 1) return tones[1];  // 3rd
      if (d === '5' && tones.length > 2) return tones[2];  // 5th
      if (d === '8') return tones[0];                       // root (octave doubling)
      return null;
    };
    const tenorTone = digitToTone(disposition[1]);
    const altoTone = digitToTone(disposition[2]);
    const sopranoTone = digitToTone(disposition[3]);
    if (tenorTone && altoTone && sopranoTone) {
      const pickInRange = (tone: ScaleDegreeNote, range: { min: number; max: number }, above: number): number | null => {
        const candidates = pitchesInRange(tone, range).filter(c => c > above);
        if (candidates.length === 0) {
          const all = pitchesInRange(tone, range);
          return all.length > 0 ? all[Math.floor(all.length / 2)] : null;
        }
        return candidates[0]; // lowest above threshold
      };
      const tenor = pickInRange(tenorTone, VOICE_RANGES.tenor, bassMidi);
      const alto = tenor != null ? pickInRange(altoTone, VOICE_RANGES.alto, tenor) : null;
      const soprano = alto != null ? pickInRange(sopranoTone, VOICE_RANGES.soprano, alto) : null;
      if (tenor != null && alto != null && soprano != null) {
        return { soprano, alto, tenor, bass: bassMidi };
      }
    }
    // Fallback to auto if disposition can't be satisfied
  }

  // ── Fixed soprano path ──────────────────────────────────────────────
  if (fixedSoprano != null) {
    // Validate that the fixed soprano belongs to the chord's pitch classes
    const chordPcs = new Set(tones.map(t => toneToMidiPc(t)));
    const sopPc = ((fixedSoprano % 12) + 12) % 12;
    if (!chordPcs.has(sopPc)) {
      // Non-chord tone in soprano — still accept it (passing tone, appoggiatura)
      // but we can't guarantee a clean voicing. Try anyway.
    }

    // Remaining tones to assign to alto & tenor (exclude soprano's PC and bass's PC)
    const usedPcs = [sopPc, toneToMidiPc(bassTone)];
    const remainingTones = tones.filter(t => !usedPcs.includes(toneToMidiPc(t)));

    // We need 2 inner voices. If not enough remaining tones, double the root.
    const innerTones: ScaleDegreeNote[] = [...remainingTones];
    while (innerTones.length < 2) innerTones.push(tones[0]); // double root
    if (innerTones.length > 2) innerTones.length = 2;

    // Assign tenor, then alto — close position above bass, below soprano
    const innerRanges = [VOICE_RANGES.tenor, VOICE_RANGES.alto];
    const innerMidis: number[] = [];
    let lastMidi = bassMidi;

    for (let vi = 0; vi < 2; vi++) {
      const tone = innerTones[vi];
      const candidates = pitchesInRange(tone, innerRanges[vi])
        .filter(c => c > bassMidi && c < fixedSoprano);
      if (candidates.length === 0) {
        // Fallback: any candidate in range
        const fallback = pitchesInRange(tone, innerRanges[vi]);
        if (fallback.length === 0) return null;
        let best = fallback[0];
        for (const c of fallback) {
          if (Math.abs(c - lastMidi) < Math.abs(best - lastMidi)) best = c;
        }
        innerMidis.push(best);
      } else {
        // Pick closest above lastMidi
        let best = candidates[0];
        for (const c of candidates) {
          if (c >= lastMidi && (c - lastMidi) < (best - lastMidi)) best = c;
        }
        innerMidis.push(best);
      }
      lastMidi = innerMidis[innerMidis.length - 1];
    }

    return { soprano: fixedSoprano, alto: innerMidis[1], tenor: innerMidis[0], bass: bassMidi };
  }

  // Upper voices: distribute remaining chord tones + smart doubling
  const upperTones: ScaleDegreeNote[] = [];

  // Detect chord properties for doubling decisions
  const isLeadingToneFirst = tonicPc != null &&
    ((toneToMidiPc(tones[0]) + 12) % 12) === ((tonicPc + 11) % 12);
  const isDiminishedFirst = tones.length >= 3 &&
    ((toneToMidiPc(tones[2]) - toneToMidiPc(tones[0]) + 12) % 12) === 6;

  // Tonal notes: PCs of I, IV, V — always safe to double
  const tonalPcsFirst = tonicPc != null
    ? [tonicPc, (tonicPc + 5) % 12, (tonicPc + 7) % 12]
    : [];

  function bestDoublingFirst(ts: ScaleDegreeNote[]): ScaleDegreeNote {
    for (const t of ts) {
      const pc = ((toneToMidiPc(t) + 12) % 12);
      if (tonalPcsFirst.includes(pc)) return t;
    }
    if (!isLeadingToneFirst) return ts[0];
    return ts[1];
  }

  if (tones.length === 3) {
    for (let i = 0; i < tones.length; i++) {
      if (i !== bassToneIndex) upperTones.push(tones[i]);
    }
    // Smart doubling choice
    if (inversion === 2) {
      // 6/4: double the bass (= 5th)
      upperTones.push(tones[bassToneIndex]);
    } else if (isLeadingToneFirst || (inversion === 1 && isDiminishedFirst)) {
      // Leading-tone or dim 1st inv: double best tonal note (not root)
      upperTones.push(bestDoublingFirst(tones.filter((_, i) => i !== 0)));
    } else {
      // Default: double the best tonal note
      upperTones.push(bestDoublingFirst(tones));
    }
  } else {
    // Seventh chord: all 4 tones, bass already has one
    for (let i = 0; i < tones.length; i++) {
      if (i !== bassToneIndex) upperTones.push(tones[i]);
    }
  }

  // We need exactly 3 upper voices (soprano, alto, tenor)
  // Sort tones by their natural pitch class to assign from bottom (tenor) to top (soprano)
  if (upperTones.length < 3) {
    // Shouldn't happen, but safety: double root
    while (upperTones.length < 3) upperTones.push(tones[0]);
  }
  if (upperTones.length > 3) {
    upperTones.length = 3; // truncate
  }

  // For each upper voice, find the best MIDI pitch in range above bass
  const voices: { name: string; range: { min: number; max: number } }[] = [
    { name: 'tenor', range: VOICE_RANGES.tenor },
    { name: 'alto', range: VOICE_RANGES.alto },
    { name: 'soprano', range: VOICE_RANGES.soprano },
  ];

  // Try ALL permutations of upper tones to find the best voicing
  const permsFirst = permutations3();
  let bestVoicing: SATBVoicing | null = null;
  let bestScore = Infinity;

  const bassPc = ((bassMidi % 12) + 12) % 12;
  // Tonal notes for doubling preference
  const tonalPcsFC = tonicPc != null
    ? [tonicPc, (tonicPc + 5) % 12, (tonicPc + 7) % 12]
    : [];

  for (const perm of permsFirst) {
    const midis: number[] = []; // tenor, alto, soprano
    let valid = true;
    let lastMidi = bassMidi;

    for (let vi = 0; vi < 3; vi++) {
      const tone = upperTones[perm[vi]];
      const candidates = pitchesInRange(tone, voices[vi].range);
      if (candidates.length === 0) { valid = false; break; }

      // Pick closest pitch above lastMidi (close position)
      let best = candidates[0];
      let bestDist = Infinity;
      for (const c of candidates) {
        if (c >= lastMidi) {
          const dist = c - lastMidi;
          if (dist < bestDist) {
            bestDist = dist;
            best = c;
          }
        }
      }
      if (bestDist === Infinity) {
        best = candidates[candidates.length - 1];
      }
      midis.push(best);
      lastMidi = best;
    }

    if (!valid || midis.length < 3) continue;

    const [t, a, s] = midis;
    let score = 0;

    // Prefer soprano on tonic or 3rd over 5th (better for cadential voice leading)
    const sopPcFC = ((s % 12) + 12) % 12;
    if (sopPcFC === bassPc) score += 30; // soprano same PC as bass → limits voice leading
    if (tonicPc != null && sopPcFC === tonicPc) score -= 10; // soprano on tonic → great
    // Soprano on 3rd is also good for variety
    if (tones.length >= 2) {
      const thirdPc = ((toneToMidiPc(tones[1]) + 12) % 12);
      if (sopPcFC === thirdPc) score -= 5;
    }

    // Spacing: prefer well-spaced voicing
    if (a - t > 12) score += 50;
    if (s - a > 12) score += 50;

    // Voice crossing
    if (t > a || a > s || bassMidi > t) score += 100;

    if (score < bestScore) {
      bestScore = score;
      bestVoicing = { soprano: s, alto: a, tenor: t, bass: bassMidi };
    }
  }

  if (bestVoicing) return bestVoicing;

  // Fallback: stacked close position (original logic)
  const assignments: number[] = [];
  let lastMidiFb = bassMidi;
  for (let vi = 0; vi < 3; vi++) {
    const tone = upperTones[vi];
    const candidates = pitchesInRange(tone, voices[vi].range);
    if (candidates.length === 0) return null;
    let best = candidates[0];
    let bestDist = Infinity;
    for (const c of candidates) {
      if (c >= lastMidiFb) {
        const dist = c - lastMidiFb;
        if (dist < bestDist) { bestDist = dist; best = c; }
      }
    }
    if (bestDist === Infinity) best = candidates[candidates.length - 1];
    assignments.push(best);
    lastMidiFb = best;
  }

  // Check spacing: S-A ≤ octave, A-T ≤ octave (standard rule)
  const [tenor, alto, soprano] = assignments;
  if (alto - tenor > 12 || soprano - alto > 12) {
    // Try to fix by adjusting — for now accept it (violations will be reported)
  }

  return { soprano, alto, tenor, bass: bassMidi };
}

/**
 * Realize subsequent chords using voice leading from previous voicing.
 * Strategy: for each voice, find the chord tone that minimizes motion,
 * respecting voice ranges and avoiding parallel 5ths/8ves.
 */
export function realizeNextChord(
  tones: ScaleDegreeNote[],
  inversion: number,
  prev: SATBVoicing,
  rules: ChoralRules,
  fixedSoprano?: number,
  fixedBass?: number,
  tonicPc?: number,
  prevSeventhPc?: number,
  isLastChord?: boolean
): SATBVoicing | null {
  if (tones.length < 3) return null;

  // 1. Place bass note based on inversion
  const bassToneIndex = inversion % tones.length;
  const bassTone = tones[bassToneIndex];
  const bassCandidates = pitchesInRange(bassTone, VOICE_RANGES.bass);
  if (bassCandidates.length === 0) return null;

  // Choose bass closest to previous bass
  // Choose bass: prefer closest that stays below tenor, with strong crossing avoidance
  let bassMidi = bassCandidates[0];
  let bestBassScore = Infinity;
  for (const c of bassCandidates) {
    let score = midiDistance(c, prev.bass);
    // Heavy penalty for bass above previous tenor (almost always wrong)
    if (c > prev.tenor) score += 200;
    // Mild penalty for bass above previous alto (extreme crossing)
    if (c > prev.alto) score += 400;
    if (score < bestBassScore) {
      bestBassScore = score;
      bassMidi = c;
    }
  }

  // Override bass with fixed value ("basso dato")
  if (fixedBass != null) bassMidi = fixedBass;

  // ── Fixed soprano path ──────────────────────────────────────────────
  if (fixedSoprano != null) {
    const sopPc = ((fixedSoprano % 12) + 12) % 12;
    const bassPc = toneToMidiPc(bassTone);

    // Remaining chord tones for alto & tenor
    const usedPcs = new Set([sopPc, bassPc]);
    const remainingTones = tones.filter(t => !usedPcs.has(toneToMidiPc(t)));
    const innerTones: ScaleDegreeNote[] = [...remainingTones];
    while (innerTones.length < 2) innerTones.push(tones[0]);
    if (innerTones.length > 2) innerTones.length = 2;

    // Try all permutations of 2 inner tones → tenor, alto
    const innerPerms = [[0, 1], [1, 0]];
    const innerRanges = [VOICE_RANGES.tenor, VOICE_RANGES.alto];
    const prevInner = [prev.tenor, prev.alto];

    let bestVoicing: SATBVoicing | null = null;
    let bestCost = Infinity;

    for (const perm of innerPerms) {
      const midis: number[] = [];
      let valid = true;
      let cost = 0;

      for (let vi = 0; vi < 2; vi++) {
        const tone = innerTones[perm[vi]];
        const candidates = pitchesInRange(tone, innerRanges[vi]);
        if (candidates.length === 0) { valid = false; break; }

        let best = candidates[0];
        let bestDist = Infinity;
        for (const c of candidates) {
          const d = midiDistance(c, prevInner[vi]);
          if (d < bestDist) { bestDist = d; best = c; }
        }
        midis.push(best);
        cost += bestDist;
      }

      if (!valid) continue;

      const [tenor, alto] = midis;

      // Crossing penalty
      if (!rules.allowCrossing) {
        if (bassMidi > tenor || tenor > alto || alto > fixedSoprano) cost += 100;
      }

      // Overlap penalty
      if (!rules.allowOverlap && prevInner) {
        if (tenor < prevInner[3]) cost += 300;  // tenor below prev bass
        if (bassMidi > prevInner[2]) cost += 300;  // bass above prev tenor
        if (alto < prevInner[2]) cost += 300;  // alto below prev tenor
        if (tenor > prevInner[1]) cost += 300;  // tenor above prev alto
        if (fixedSoprano < prevInner[1]) cost += 300;  // soprano below prev alto
        if (alto > prevInner[0]) cost += 300;  // alto above prev soprano
      }

      // Spacing penalty
      if (alto - tenor > 12) cost += 80;
      if (fixedSoprano - alto > 12) cost += 80;

      // Unison penalty
      const allMidisFs = [bassMidi, tenor, alto, fixedSoprano];
      for (let u = 0; u < allMidisFs.length; u++) {
        for (let w = u + 1; w < allMidisFs.length; w++) {
          if (allMidisFs[u] === allMidisFs[w]) cost += 40;
        }
      }

      // Parallel penalty
      if (!rules.allowParallel5ths || !rules.allowParallel8ves) {
        const currNotes = [bassMidi, tenor, alto, fixedSoprano];
        const prevNotes = [prev.bass, prev.tenor, prev.alto, prev.soprano];
        cost += countParallels(prevNotes, currNotes, rules) * 200;
      }

      // ── Advanced voice-leading rules ──
      if (tonicPc != null) {
        const leadingTonePc = (tonicPc + 11) % 12;
        const currPcs = [bassMidi, tenor, alto, fixedSoprano].map(m => ((m % 12) + 12) % 12);
        if (currPcs.filter(pc => pc === leadingTonePc).length > 1) cost += 300;
      }
      const sopMotionFs = fixedSoprano - prev.soprano;
      const bassMotionFs = bassMidi - prev.bass;
      if (sopMotionFs !== 0 && bassMotionFs !== 0) {
        if (Math.sign(sopMotionFs) !== Math.sign(bassMotionFs)) {
          cost -= 8;
        } else {
          const outerInterval = Math.abs(fixedSoprano - bassMidi) % 12;
          if (outerInterval === 0 || outerInterval === 7) cost += 100;
        }
      }

      // ── Leading tone resolution (inner voices, soprano is fixed) ──
      // LT resolves to tonic when target chord contains tonic as chord tone
      if (tonicPc != null) {
        const ltPc = (tonicPc + 11) % 12;
        const chordPcs = tones.map(t => ((tonicPc + t.semiFromRoot) % 12 + 12) % 12);
        const tonicInChord = chordPcs.includes(tonicPc);
        if (tonicInChord) {
          const prevInner = [prev.bass, prev.tenor, prev.alto];
          const currInner = [bassMidi, tenor, alto];
          for (let vi = 0; vi < 3; vi++) {
            const prevPc = ((prevInner[vi] % 12) + 12) % 12;
            if (prevPc === ltPc) {
              const currPc = ((currInner[vi] % 12) + 12) % 12;
              if (currPc === tonicPc) cost -= 30;
              else cost += 150;
            }
          }
        }
      }

      // ── Seventh resolution (all voices incl. fixed soprano) ──
      // Exception: transferred resolution (scambio di parti)
      if (prevSeventhPc != null) {
        const prevAllFs = [prev.bass, prev.tenor, prev.alto, prev.soprano];
        const currAllFs = [bassMidi, tenor, alto, fixedSoprano];
        const currPcsFs = currAllFs.map(m => ((m % 12) + 12) % 12);
        const resPc1 = ((prevSeventhPc - 1) % 12 + 12) % 12;
        const resPc2 = ((prevSeventhPc - 2) % 12 + 12) % 12;
        const resTransferred = currPcsFs.some(pc => pc === resPc1 || pc === resPc2);

        for (let vi = 0; vi < 4; vi++) {
          const prevPc = ((prevAllFs[vi] % 12) + 12) % 12;
          if (prevPc === prevSeventhPc) {
            const diff = prevAllFs[vi] - currAllFs[vi];
            if (diff >= 1 && diff <= 2) cost -= 50;
            else if (resTransferred) cost += 80;
            else cost += 250;
          }
        }
      }

      // ── Seventh preparation (fixedSoprano path) ──
      if (tones.length >= 4) {
        const seventhPc = ((toneToMidiPc(tones[3]) + 12) % 12);
        const prevAll7 = [prev.bass, prev.tenor, prev.alto, prev.soprano];
        const currAll7 = [bassMidi, tenor, alto, fixedSoprano];
        for (let vi = 0; vi < 4; vi++) {
          const currPc = ((currAll7[vi] % 12) + 12) % 12;
          if (currPc === seventhPc) {
            const motion = Math.abs(currAll7[vi] - prevAll7[vi]);
            if (motion === 0) cost -= 15;
            else if (motion <= 2) cost -= 5;
            else cost += 60;
          }
        }
      }

      if (cost < bestCost) {
        bestCost = cost;
        bestVoicing = { soprano: fixedSoprano, alto, tenor, bass: bassMidi };
      }
    }

    return bestVoicing;
  }

  // 2. Upper voices: assign chord tones with minimal total motion
  const upperToneSets: ScaleDegreeNote[][] = [];

  // Determine smart doubling based on inversion, chord quality, and tonal notes
  const isLeadingTone = tonicPc != null &&
    ((toneToMidiPc(tones[0]) + 12) % 12) === ((tonicPc + 11) % 12);
  const isDiminished = tones.length >= 3 &&
    ((toneToMidiPc(tones[2]) - toneToMidiPc(tones[0]) + 12) % 12) === 6; // tritone root→5th

  // Tonal notes: PCs of I, IV, V in the key — always safe to double
  const tonalPcs = tonicPc != null
    ? [tonicPc, (tonicPc + 5) % 12, (tonicPc + 7) % 12]
    : [];

  // Find the best tone to double: prefer tonal notes, then root
  function bestDoubling(ts: ScaleDegreeNote[], excludeIdx: number): ScaleDegreeNote {
    // First: try to find a tonal note among the chord tones
    for (const t of ts) {
      const pc = ((toneToMidiPc(t) + 12) % 12);
      if (tonalPcs.includes(pc)) return t;
    }
    // Fallback: root (unless it's the leading tone)
    if (!isLeadingTone) return ts[0];
    return ts[1]; // double 3rd for LT chords
  }

  // Standard voicing
  const standardUpper: ScaleDegreeNote[] = [];
  if (tones.length === 3) {
    for (let i = 0; i < tones.length; i++) {
      if (i !== bassToneIndex) standardUpper.push(tones[i]);
    }
    // Smart doubling choice
    if (inversion === 2) {
      // 6/4 chord: double the bass note (= 5th of chord)
      standardUpper.push(tones[bassToneIndex]);
    } else if (isLeadingTone || (inversion === 1 && isDiminished)) {
      // Leading-tone or dim 1st inv: never double root
      standardUpper.push(bestDoubling(tones.filter((_, i) => i !== 0), bassToneIndex));
    } else {
      // Default: double the best tonal note
      standardUpper.push(bestDoubling(tones, bassToneIndex));
    }
  } else {
    for (let i = 0; i < tones.length; i++) {
      if (i !== bassToneIndex) standardUpper.push(tones[i]);
    }
  }
  while (standardUpper.length < 3) standardUpper.push(tones[0]);
  if (standardUpper.length > 3) standardUpper.length = 3;
  upperToneSets.push(standardUpper);

  // Alternative doublings: try each non-LT chord tone as a doubling candidate
  // so the cost function can pick the best for voice leading
  if (tones.length === 3 && inversion !== 2 && !isLeadingTone) {
    for (let di = 0; di < tones.length; di++) {
      const dPc = ((toneToMidiPc(tones[di]) + 12) % 12);
      // Skip if it's the leading tone PC
      if (tonicPc != null && dPc === ((tonicPc + 11) % 12)) continue;
      const altUpper: ScaleDegreeNote[] = [];
      for (let i = 0; i < tones.length; i++) {
        if (i !== bassToneIndex) altUpper.push(tones[i]);
      }
      altUpper.push(tones[di]);
      if (altUpper.length > 3) altUpper.length = 3;
      // Only add if different from standard
      const altKey = altUpper.map(t => t.letter + t.accidental).join(',');
      const stdKey = standardUpper.map(t => t.letter + t.accidental).join(',');
      if (altKey !== stdKey) upperToneSets.push(altUpper);
    }
  }

  // Incomplete voicing variant (triple root, skip 5th) — allowed after seventh chord resolution
  // This lets both leading tone resolve UP and 7th resolve DOWN without conflicting
  if (prevSeventhPc != null && tones.length === 3 && inversion === 0) {
    const incompleteUpper: ScaleDegreeNote[] = [tones[0], tones[0], tones[1]]; // root, root, 3rd (no 5th)
    upperToneSets.push(incompleteUpper);
  }
  // Also try incomplete voicing on last chord (for clean PAC resolution)
  if (isLastChord && tones.length === 3 && inversion === 0) {
    const incompleteUpper: ScaleDegreeNote[] = [tones[0], tones[0], tones[1]];
    // Only add if not already added
    if (prevSeventhPc == null) upperToneSets.push(incompleteUpper);
  }

  // For each permutation of upper tones to voices, compute total motion
  const voiceNames = ['tenor', 'alto', 'soprano'] as const;
  const prevMidis = [prev.tenor, prev.alto, prev.soprano];
  const ranges = [VOICE_RANGES.tenor, VOICE_RANGES.alto, VOICE_RANGES.soprano];

  // Generate all permutations of upperTones indices for 3 voices
  const perms = permutations3();

  let bestVoicing: SATBVoicing | null = null;
  let bestCost = Infinity;

  for (const upperTones of upperToneSets) {
  for (const perm of perms) {
    let totalCost = 0;
    const midis: number[] = [];
    let valid = true;

    for (let vi = 0; vi < 3; vi++) {
      const tone = upperTones[perm[vi]];
      const candidates = pitchesInRange(tone, ranges[vi]);
      if (candidates.length === 0) { valid = false; break; }

      // Pick closest to previous voice position
      let best = candidates[0];
      let bestDist = Infinity;
      for (const c of candidates) {
        const d = midiDistance(c, prevMidis[vi]);
        if (d < bestDist) {
          bestDist = d;
          best = c;
        }
      }
      midis.push(best);
      // Voice-leading cost: prefer common tones > stepwise > leaps
      if (best === prevMidis[vi]) {
        // Common tone: no penalty, bonus for staying still
        totalCost -= 4;
      } else if (bestDist <= 2) {
        // Stepwise (half/whole step): small reward
        totalCost += bestDist - 2;
      } else if (bestDist <= 4) {
        // Small skip (m3/M3): moderate cost
        totalCost += bestDist;
      } else {
        // Leap (P4+): heavier penalty
        totalCost += bestDist + (bestDist - 4) * 3;
      }
    }

    if (!valid) continue;

    const [tenor, alto, soprano] = midis;

    // Voice crossing penalty
    if (!rules.allowCrossing) {
      if (tenor > alto || alto > soprano || bassMidi > tenor) {
        totalCost += 100;
      }
    }

    // Voice overlap penalty (voice moves past where adjacent voice *was*)
    if (!rules.allowOverlap && prev) {
      if (tenor < prev.bass) totalCost += 300;
      if (bassMidi > prev.tenor) totalCost += 300;
      if (alto < prev.tenor) totalCost += 300;
      if (tenor > prev.alto) totalCost += 300;
      if (soprano < prev.alto) totalCost += 300;
      if (alto > prev.soprano) totalCost += 300;
    }

    // Spacing penalty (S-A > octave or A-T > octave)
    if (alto - tenor > 12) totalCost += 80;
    if (soprano - alto > 12) totalCost += 80;

    // Unison penalty (two voices on same MIDI)
    const allMidis = [bassMidi, tenor, alto, soprano];
    for (let u = 0; u < allMidis.length; u++) {
      for (let v = u + 1; v < allMidis.length; v++) {
        if (allMidis[u] === allMidis[v]) totalCost += 40;
      }
    }

    // Soprano doubling bass PC penalty (limits voice-leading options, risks direct 8ves)
    if (((soprano % 12) + 12) % 12 === ((bassMidi % 12) + 12) % 12) {
      totalCost += 25;
    }

    // Parallel 5ths/8ves penalty
    if (!rules.allowParallel5ths || !rules.allowParallel8ves) {
      const currNotes = [bassMidi, tenor, alto, soprano];
      const prevNotes = [prev.bass, prev.tenor, prev.alto, prev.soprano];
      const parallelPenalty = countParallels(prevNotes, currNotes, rules);
      totalCost += parallelPenalty * 200;
    }

    // ── Advanced voice-leading rules ──
    if (tonicPc != null) {
      const leadingTonePc = (tonicPc + 11) % 12;
      const currPcs = [bassMidi, tenor, alto, soprano].map(m => ((m % 12) + 12) % 12);
      // Never double leading tone
      if (currPcs.filter(pc => pc === leadingTonePc).length > 1) totalCost += 300;
    }
    // Contrary motion bonus (outer voices)
    const sopMotion = soprano - prev.soprano;
    const bassMotion = bassMidi - prev.bass;
    if (sopMotion !== 0 && bassMotion !== 0) {
      if (Math.sign(sopMotion) !== Math.sign(bassMotion)) {
        totalCost -= 8; // contrary motion rewarded
      } else {
        // Direct 5ths/8ves in outer voices penalty
        const outerInterval = Math.abs(soprano - bassMidi) % 12;
        if (outerInterval === 0 || outerInterval === 7) totalCost += 100;
      }
    }

    // ── Leading tone resolution (all voices) ──
    // Any voice with LT should resolve UP to tonic, whenever the target chord
    // contains the tonic as a chord tone (covers I, vi for deceptive cadence, etc.)
    if (tonicPc != null) {
      const ltPc = (tonicPc + 11) % 12;
      // Check if tonic PC exists among the current chord tones
      const chordPcs = tones.map(t => ((tonicPc + t.semiFromRoot) % 12 + 12) % 12);
      const tonicInChord = chordPcs.includes(tonicPc);
      if (tonicInChord) {
        const prevAll = [prev.bass, prev.tenor, prev.alto, prev.soprano];
        const currAll = [bassMidi, tenor, alto, soprano];
        for (let vi = 0; vi < 4; vi++) {
          const prevPc = ((prevAll[vi] % 12) + 12) % 12;
          if (prevPc === ltPc) {
            const currPc = ((currAll[vi] % 12) + 12) % 12;
            if (currPc === tonicPc) {
              totalCost -= 30; // strong bonus for resolving LT → tonic
            } else {
              // heavier penalty in soprano (vi===3) than inner voices
              totalCost += vi === 3 ? 250 : 150;
            }
          }
        }
      }
    }

    // ── Seventh resolution: 7th must resolve DOWN by step ──
    // Exception: "Scambio di Parti" — the 7th can rise/hold if its resolution
    // pitch class (down 1-2 semitones) appears in ANOTHER voice (transferred resolution).
    if (prevSeventhPc != null) {
      const prevAll = [prev.bass, prev.tenor, prev.alto, prev.soprano];
      const currAll = [bassMidi, tenor, alto, soprano];
      const currPcsAll = currAll.map(m => ((m % 12) + 12) % 12);
      // Resolution targets: one or two semitones below the 7th
      const resPc1 = ((prevSeventhPc - 1) % 12 + 12) % 12;
      const resPc2 = ((prevSeventhPc - 2) % 12 + 12) % 12;
      // Check if resolution PC exists anywhere in the current chord
      const resolutionTransferred = currPcsAll.some(pc => pc === resPc1 || pc === resPc2);

      for (let vi = 0; vi < 4; vi++) {
        const prevPc = ((prevAll[vi] % 12) + 12) % 12;
        if (prevPc === prevSeventhPc) {
          const diff = prevAll[vi] - currAll[vi]; // positive = resolved down
          if (diff >= 1 && diff <= 2) {
            totalCost -= 50; // strong bonus for resolving 7th down by step
          } else if (resolutionTransferred) {
            // Transferred resolution: another voice took the resolution note
            // Only a small penalty (prefer direct resolution but allow transfer)
            totalCost += 80; // transferred resolution: accept reluctantly
          } else {
            totalCost += 250; // penalty for truly unresolved 7th
          }
        }
      }
    }

    // ── Seventh preparation: 7th should arrive by step or common tone ──
    if (tones.length >= 4) {
      const seventhPc = ((toneToMidiPc(tones[3]) + 12) % 12);
      const prevAll7 = [prev.bass, prev.tenor, prev.alto, prev.soprano];
      const currAll7 = [bassMidi, tenor, alto, soprano];
      for (let vi = 0; vi < 4; vi++) {
        const currPc = ((currAll7[vi] % 12) + 12) % 12;
        if (currPc === seventhPc) {
          const motion = Math.abs(currAll7[vi] - prevAll7[vi]);
          if (motion === 0) {
            totalCost -= 15; // best: common tone preparation
          } else if (motion <= 2) {
            totalCost -= 5; // good: stepwise preparation
          } else {
            totalCost += 60; // penalty: unprepared 7th (leap)
          }
        }
      }
    }

    if (totalCost < bestCost) {
      bestCost = totalCost;
      bestVoicing = { soprano, alto, tenor, bass: bassMidi };
    }
  } // end perm loop
  } // end upperToneSets loop

  return bestVoicing;
}

/** Generate all 6 permutations of [0,1,2]. */
function permutations3(): number[][] {
  return [
    [0, 1, 2], [0, 2, 1],
    [1, 0, 2], [1, 2, 0],
    [2, 0, 1], [2, 1, 0],
  ];
}

/** Count parallel 5ths and 8ves between two SATB snapshots. */
function countParallels(prevMidis: number[], currMidis: number[], rules: ChoralRules): number {
  let count = 0;
  for (let i = 0; i < 4; i++) {
    for (let j = i + 1; j < 4; j++) {
      const prevInterval = ((prevMidis[j] - prevMidis[i]) % 12 + 12) % 12;
      const currInterval = ((currMidis[j] - currMidis[i]) % 12 + 12) % 12;

      // Both voices must actually move for it to be "parallel"
      if (prevMidis[i] === currMidis[i] && prevMidis[j] === currMidis[j]) continue;
      // At least one voice must move
      if (prevMidis[i] === currMidis[i] || prevMidis[j] === currMidis[j]) continue;

      // Same direction?
      const dir_i = Math.sign(currMidis[i] - prevMidis[i]);
      const dir_j = Math.sign(currMidis[j] - prevMidis[j]);
      if (dir_i !== dir_j) continue; // contrary/oblique motion — OK

      // Parallel 5th
      if (!rules.allowParallel5ths && prevInterval === 7 && currInterval === 7) count++;
      // Parallel 8ve
      if (!rules.allowParallel8ves && prevInterval === 0 && currInterval === 0 && prevMidis[i] !== prevMidis[j]) count++;
    }
  }
  return count;
}

// ─── Violation Detection ───────────────────────────────────────────────────

/**
 * Detect voice-leading violations between two adjacent voicings.
 */
export function detectViolations(
  prev: SATBVoicing,
  curr: SATBVoicing,
  measure: number,
  beat: number,
  rules: ChoralRules
): ChoralViolation[] {
  const violations: ChoralViolation[] = [];
  const voiceLabels = ['bass', 'tenor', 'alto', 'soprano'];
  const prevArr = [prev.bass, prev.tenor, prev.alto, prev.soprano];
  const currArr = [curr.bass, curr.tenor, curr.alto, curr.soprano];

  // Voice crossing
  if (!rules.allowCrossing) {
    if (curr.bass > curr.tenor) violations.push({ type: 'voice-crossing', description: 'Bass crosses above tenor', measure, beat, voices: ['bass', 'tenor'] });
    if (curr.tenor > curr.alto) violations.push({ type: 'voice-crossing', description: 'Tenor crosses above alto', measure, beat, voices: ['tenor', 'alto'] });
    if (curr.alto > curr.soprano) violations.push({ type: 'voice-crossing', description: 'Alto crosses above soprano', measure, beat, voices: ['alto', 'soprano'] });
  }

  // Voice overlap
  if (!rules.allowOverlap) {
    if (curr.tenor < prev.bass) violations.push({ type: 'voice-overlap', description: 'Tenor goes below previous bass', measure, beat, voices: ['tenor', 'bass'] });
    if (curr.bass > prev.tenor) violations.push({ type: 'voice-overlap', description: 'Bass goes above previous tenor', measure, beat, voices: ['bass', 'tenor'] });
    if (curr.alto < prev.tenor) violations.push({ type: 'voice-overlap', description: 'Alto goes below previous tenor', measure, beat, voices: ['alto', 'tenor'] });
    if (curr.tenor > prev.alto) violations.push({ type: 'voice-overlap', description: 'Tenor goes above previous alto', measure, beat, voices: ['tenor', 'alto'] });
    if (curr.soprano < prev.alto) violations.push({ type: 'voice-overlap', description: 'Soprano goes below previous alto', measure, beat, voices: ['soprano', 'alto'] });
    if (curr.alto > prev.soprano) violations.push({ type: 'voice-overlap', description: 'Alto goes above previous soprano', measure, beat, voices: ['alto', 'soprano'] });
  }

  // Spacing (S-A ≤ 8ve, A-T ≤ 8ve, T-B can be more)
  if (curr.soprano - curr.alto > 12) violations.push({ type: 'spacing', description: 'Soprano-Alto exceeds an octave', measure, beat, voices: ['soprano', 'alto'] });
  if (curr.alto - curr.tenor > 12) violations.push({ type: 'spacing', description: 'Alto-Tenor exceeds an octave', measure, beat, voices: ['alto', 'tenor'] });

  // Range
  for (const [vName, midi] of [['soprano', curr.soprano], ['alto', curr.alto], ['tenor', curr.tenor], ['bass', curr.bass]] as [string, number][]) {
    const range = VOICE_RANGES[vName];
    if (midi < range.min || midi > range.max) {
      violations.push({ type: 'range', description: `${vName} out of range (MIDI ${midi})`, measure, beat, voices: [vName] });
    }
  }

  // Parallel 5ths / 8ves
  for (let i = 0; i < 4; i++) {
    for (let j = i + 1; j < 4; j++) {
      const prevInterval = ((prevArr[j] - prevArr[i]) % 12 + 12) % 12;
      const currInterval = ((currArr[j] - currArr[i]) % 12 + 12) % 12;

      if (prevArr[i] === currArr[i] && prevArr[j] === currArr[j]) continue;
      if (prevArr[i] === currArr[i] || prevArr[j] === currArr[j]) continue;

      const dir_i = Math.sign(currArr[i] - prevArr[i]);
      const dir_j = Math.sign(currArr[j] - prevArr[j]);
      if (dir_i !== dir_j) continue;

      if (!rules.allowParallel5ths && prevInterval === 7 && currInterval === 7) {
        violations.push({ type: 'parallel-5th', description: `Parallel 5ths: ${voiceLabels[i]}-${voiceLabels[j]}`, measure, beat, voices: [voiceLabels[i], voiceLabels[j]] });
      }
      if (!rules.allowParallel8ves && prevInterval === 0 && currInterval === 0 && prevArr[i] !== prevArr[j]) {
        violations.push({ type: 'parallel-8ve', description: `Parallel 8ves: ${voiceLabels[i]}-${voiceLabels[j]}`, measure, beat, voices: [voiceLabels[i], voiceLabels[j]] });
      }
    }
  }

  return violations;
}

// ─── StaffNote Generation ──────────────────────────────────────────────────

let noteIdCounter = 0;
let noteIdPrefix = Date.now().toString(36);

/** Reset the ID counter (useful for testing). */
export function resetNoteIdCounter(): void {
  noteIdCounter = 0;
  noteIdPrefix = Date.now().toString(36);
}

/** Generate a unique note ID. */
function nextNoteId(): string {
  return `ch_${noteIdPrefix}_${++noteIdCounter}`;
}

/**
 * Convert an SATB voicing at a specific beat/measure into StaffNote[].
 * Produces 4 notes (one per voice) compatible with GrandStaffEditor.
 */
export function voicingToStaffNotes(
  voicing: SATBVoicing,
  measure: number,
  beat: number,
  duration: string,
  tones: ScaleDegreeNote[],
  inversion: number,
  keySignature: KeySignature
): StaffNote[] {
  const voiceMap: { midi: number; voice: Voice; clef: 'treble' | 'bass'; tonePick: ScaleDegreeNote }[] = [
    { midi: voicing.soprano, voice: 1, clef: 'treble', tonePick: findToneForMidi(voicing.soprano, tones) },
    { midi: voicing.alto,    voice: 2, clef: 'treble', tonePick: findToneForMidi(voicing.alto, tones) },
    { midi: voicing.tenor,   voice: 3, clef: 'bass',   tonePick: findToneForMidi(voicing.tenor, tones) },
    { midi: voicing.bass,    voice: 4, clef: 'bass',   tonePick: findToneForMidi(voicing.bass, tones) },
  ];

  const notes: StaffNote[] = [];

  for (const v of voiceMap) {
    const { letter, accidental } = v.tonePick;
    const octave = Math.floor(v.midi / 12) - 1;
    const noteIndex = midiToNoteIndex(v.midi);
    const position = notePosition(letter, octave);

    // Calculate explicit accidental relative to key signature
    const sharpNotes = ['F', 'C', 'G', 'D', 'A', 'E', 'B'].slice(0, keySignature.type === 'sharp' ? keySignature.count : 0);
    const flatNotes = ['B', 'E', 'A', 'D', 'G', 'C', 'F'].slice(0, keySignature.type === 'flat' ? keySignature.count : 0);

    let explicitAccidental: string | null = null;
    if (keySignature.type === 'sharp') {
      const isInKeySig = sharpNotes.includes(letter);
      if (accidental === '#' && !isInKeySig) explicitAccidental = 'sharp';
      else if (accidental === '' && isInKeySig) explicitAccidental = 'natural';
      else if (accidental === 'b') explicitAccidental = 'flat';
      else if (accidental === '##') explicitAccidental = 'double-sharp';
      else if (accidental === 'bb') explicitAccidental = 'double-flat';
    } else {
      const isInKeySig = flatNotes.includes(letter);
      if (accidental === 'b' && !isInKeySig) explicitAccidental = 'flat';
      else if (accidental === '' && isInKeySig) explicitAccidental = 'natural';
      else if (accidental === '#') explicitAccidental = 'sharp';
      else if (accidental === '##') explicitAccidental = 'double-sharp';
      else if (accidental === 'bb') explicitAccidental = 'double-flat';
    }

    // Compute tick position
    const beatsPerQuarter = 1; // quarter-note base
    const durationBeats = DURATION_VALUES[duration as keyof typeof DURATION_VALUES] ?? 1;
    const startTick = ((measure * 4) + (beat - 1)) * TICKS_PER_QUARTER; // assumes 4/4 for now
    const durationTicks = durationBeats * TICKS_PER_QUARTER;

    const note: StaffNote = {
      id: nextNoteId(),
      pitch: letter,
      octave,
      position,
      midi: v.midi,
      noteIndex,
      clef: v.clef,
      explicitAccidental: explicitAccidental as any,
      duration: duration as any,
      isRest: false,
      isTriplet: false,
      isDuplet: false,
      isDotted: false,
      measureIndex: measure,
      beat,
      voice: v.voice,
      startTick,
      durationTicks,
    };

    notes.push(note);
  }

  return notes;
}

/** Find the ScaleDegreeNote whose pitch class matches a MIDI value. */
function findToneForMidi(midi: number, tones: ScaleDegreeNote[]): ScaleDegreeNote {
  const pc = midiToNoteIndex(midi);
  for (const t of tones) {
    const tPc = ((LETTER_TO_SEMI[t.letter] ?? 0) +
      (t.accidental === '#' ? 1 : t.accidental === 'b' ? -1 :
       t.accidental === '##' ? 2 : t.accidental === 'bb' ? -2 : 0) + 12) % 12;
    if (tPc === pc) return t;
  }
  // Fallback: return first tone
  return tones[0];
}

// ─── Main Entry Point ──────────────────────────────────────────────────────

/**
 * Realize a chorale from a roman numeral progression.
 *
 * @param progression - Array of RomanChord descriptors
 * @param config - Tonic, mode, time signature, rules
 * @returns StaffNote[] for GrandStaffEditor + violations list
 */
/**
 * Parse a modulation token like 'G', 'g', 'Bb', 'f#' → { tonic, isMinor }.
 * Upper-case first letter = major, lower-case = minor.
 * Returns null if the token is not a valid modulation.
 */
export function parseModulationToken(token: string): { tonic: string; isMinor: boolean } | null {
  if (!token || token.length === 0) return null;
  const m = token.match(/^([A-Ga-g])(b{1,2}|#{1,2})?$/);
  if (!m) return null;
  const letter = m[1];
  const acc = m[2] ?? '';
  const isMinor = letter === letter.toLowerCase();
  const tonic = letter.toUpperCase() + acc;
  return { tonic, isMinor };
}

export function realizeChorale(
  progression: RomanChord[],
  config: ChoralConfig
): ChoralRealizationResult {
  const { tonic: initialTonic, isMinor: initialIsMinor, timeSignature } = config;
  const rules: ChoralRules = {
    allowParallel5ths: false,
    allowParallel8ves: false,
    allowCrossing: false,
    allowOverlap: false,
    doubleRoot: true,
    ...config.rules,
  };

  resetNoteIdCounter();

  // Current tonality — may change via modulation tokens
  let tonic = initialTonic;
  let isMinor = initialIsMinor;
  let scale = buildScale(tonic, isMinor);
  let keySignature = buildKeySignature(tonic, isMinor);
  let tonicPcVal = noteNameToPc(tonic);

  // The display key signature never changes — the staff always shows the original
  // armature. Accidentals are computed relative to this.
  const displayKeySignature = buildKeySignature(initialTonic, initialIsMinor);

  const allNotes: StaffNote[] = [];
  const allViolations: ChoralViolation[] = [];
  const modulationContexts: ModulationContext[] = [];
  let prevVoicing: SATBVoicing | null = null;
  let prevSeventhPc: number | null = null;

  // Build soprano constraint lookup map: "measure:beat" → MIDI
  const sopranoMap = new Map<string, number>();
  if (config.sopranoMelody) {
    for (const sc of config.sopranoMelody) {
      sopranoMap.set(`${sc.measure}:${sc.beat}`, sc.midi);
    }
  }

  // Build bass constraint lookup map: "measure:beat" → MIDI ("basso dato")
  const bassMap = new Map<string, number>();
  if (config.bassMelody) {
    for (const bc of config.bassMelody) {
      bassMap.set(`${bc.measure}:${bc.beat}`, bc.midi);
    }
  }

  // Compute beat duration for each chord (fill to next chord or end of measure)
  const sortedProg = [...progression].sort((a, b) =>
    a.measure !== b.measure ? a.measure - b.measure : a.beat - b.beat
  );

  for (let i = 0; i < sortedProg.length; i++) {
    const chord = sortedProg[i];

    // ── Modulation: switch tonality if this chord has a modulateTo marker ──
    if (chord.modulateTo) {
      const mod = parseModulationToken(chord.modulateTo);
      if (mod) {
        tonic = mod.tonic;
        isMinor = mod.isMinor;
        scale = buildScale(tonic, isMinor);
        keySignature = buildKeySignature(tonic, isMinor);
        tonicPcVal = noteNameToPc(tonic);
        // Emit a modulation context for the analysis engine
        const beatsPerMeasure = timeSignature.numerator * (4 / timeSignature.denominator);
        const absBeat = chord.measure * beatsPerMeasure + (chord.beat - 1);
        modulationContexts.push({
          absBeat,
          measureIndex: chord.measure,
          beat: chord.beat,
          newTonic: tonic,
          newIsMinor: isMinor,
          label: `→ ${tonic} ${isMinor ? 'min' : 'Maj'}`,
          source: 'composer',
        });
      }
    }

    const parsed = parseRoman(chord.roman);
    let inv = chord.inversion ?? parsed.inversion;
    // ── Smart inversion defaults (when user/parser didn't specify) ──
    if (chord.inversion == null && parsed.inversion === 0) {
      // vii° → always 1st inversion (vii°6) — dim triad unstable in root position
      if (parsed.degree === 6 && !parsed.hasSeventh) inv = 1;
      // ii → prefer 1st inversion (ii6) when preceding V
      if (parsed.degree === 1 && i + 1 < sortedProg.length) {
        const nextParsed = parseRoman(sortedProg[i + 1].roman);
        if (nextParsed.degree === 4) inv = 1;
      }
      // I6/4 cadenzale: I before V → 2nd inversion (cadential 6/4)
      if (parsed.degree === 0 && i + 1 < sortedProg.length) {
        const nextParsed = parseRoman(sortedProg[i + 1].roman);
        if (nextParsed.degree === 4) inv = 2;
      }
    }
    const tones = getChordTones(parsed, scale, tonic, isMinor);

    // Determine duration: explicit > fill to next chord > end of measure
    const beatsPerMeasure = timeSignature.numerator * (4 / timeSignature.denominator);
    let durationName: string;
    if (chord.duration) {
      durationName = chord.duration;
    } else {
      let durationBeats: number;
      if (i + 1 < sortedProg.length && sortedProg[i + 1].measure === chord.measure) {
        durationBeats = sortedProg[i + 1].beat - chord.beat;
      } else if (i + 1 < sortedProg.length) {
        durationBeats = (beatsPerMeasure - chord.beat + 1);
      } else {
        durationBeats = beatsPerMeasure - chord.beat + 1;
      }
      durationName = beatsToDuration(durationBeats);
    }

    // Soprano constraint for this chord position
    let fixedSoprano = sopranoMap.get(`${chord.measure}:${chord.beat}`);
    const fixedBass = bassMap.get(`${chord.measure}:${chord.beat}`);

    // ── Cadence enforcement ──
    const isLast = (i === sortedProg.length - 1);
    // PAC: last chord is I in root position → soprano should be on tonic
    if (isLast && parsed.degree === 0 && inv === 0 && fixedSoprano == null) {
      // Find tonic MIDI in soprano range closest to previous soprano
      const tonicCandidates = pitchesInRange(tones[0], VOICE_RANGES.soprano);
      if (tonicCandidates.length > 0 && prevVoicing) {
        let bestTonic = tonicCandidates[0];
        let bestDist = Infinity;
        for (const c of tonicCandidates) {
          const d = midiDistance(c, prevVoicing.soprano);
          if (d < bestDist) { bestDist = d; bestTonic = c; }
        }
        fixedSoprano = bestTonic;
      }
    }

    // Realize voicing
    let voicing: SATBVoicing | null;
    if (!prevVoicing) {
      voicing = realizeFirstChord(tones, inv, rules, fixedSoprano, fixedBass, tonicPcVal, config.initialDisposition);
    } else {
      voicing = realizeNextChord(tones, inv, prevVoicing, rules, fixedSoprano, fixedBass, tonicPcVal, prevSeventhPc ?? undefined, i === sortedProg.length - 1);
    }

    if (!voicing) continue;

    // Detect violations
    if (prevVoicing) {
      const violations = detectViolations(prevVoicing, voicing, chord.measure, chord.beat, rules);
      allViolations.push(...violations);
    }

    // Generate StaffNotes
    const notes = voicingToStaffNotes(voicing, chord.measure, chord.beat, durationName, tones, inv, displayKeySignature);
    allNotes.push(...notes);

    prevVoicing = voicing;
    // Track seventh PC for next chord's resolution check
    prevSeventhPc = tones.length >= 4 ? toneToMidiPc(tones[3]) : null;
  }

  return { notes: allNotes, violations: allViolations, modulationContexts };
}

// ─── Auto-Harmonization ────────────────────────────────────────────────────

/**
 * Diatonic roman numerals for each degree in major and minor keys.
 * Used both for display and for chord-tone PC sets.
 */
const DIATONIC_ROMANS_MAJOR = ['I', 'ii', 'iii', 'IV', 'V', 'vi', 'viio'] as const;
const DIATONIC_ROMANS_MINOR = ['i', 'iio', 'III', 'iv', 'V', 'VI', 'viio'] as const;

/**
 * Choose the best inversion for a chord to create a smooth bass line.
 *
 * Strategy:
 * - First and last chords: prefer root position (stable cadence points).
 * - Middle chords: pick the inversion whose bass PC is closest (by semitone distance)
 *   to the previous bass, preferring root position on ties.
 */
function chooseBestInversion(
  deg: number,
  triadPcSets: number[][],
  tonicPc: number,
  prevBassMidi: number,
  isFirst: boolean,
  isLast: boolean
): number {
  const pcs = triadPcSets[deg]; // [root, 3rd, 5th]

  // First/last chord → root position for stability
  if (isFirst || isLast || prevBassMidi < 0) return 0;

  // Try inversions 0, 1, 2 and pick the one with smoothest bass motion
  let bestInv = 0;
  let bestDist = Infinity;
  const prevPc = ((prevBassMidi % 12) + 12) % 12;

  for (let inv = 0; inv < pcs.length; inv++) {
    const bassPc = pcs[inv];
    // Semitone distance (circular)
    let dist = Math.abs(bassPc - prevPc);
    if (dist > 6) dist = 12 - dist;

    // Slight preference for root position (add 0.5 penalty for inversions)
    const adjustedDist = inv === 0 ? dist : dist + 0.5;

    // Penalize 6/4 (2nd inversion) more in general — it's weaker
    const penalty64 = inv === 2 ? 1.5 : 0;

    if (adjustedDist + penalty64 < bestDist) {
      bestDist = adjustedDist + penalty64;
      bestInv = inv;
    }
  }
  return bestInv;
}

/**
 * Get a representative bass MIDI pitch class for a given degree + inversion.
 * Returns a MIDI value in the bass range (octave 2-3) for distance comparisons.
 */
function bassMidiForInversion(
  _deg: number,
  inv: number,
  triadPcSets: number[][],
  _tonicPc: number
): number {
  const pcs = triadPcSets[_deg];
  const bassPc = pcs[inv % pcs.length];
  // Put it in octave 3 (MIDI 48-59) for consistent distance calculations
  return 48 + bassPc;
}

/**
 * Return the figured bass suffix for a given inversion (triads only).
 * @param inv  - 0=root, 1=first, 2=second
 * @param isSeventh - true for seventh chords (future use)
 */
function inversionSuffix(inv: number, isSeventh: boolean): string {
  if (isSeventh) {
    switch (inv) {
      case 0: return '7';
      case 1: return '6/5';
      case 2: return '4/3';
      case 3: return '4/2';
      default: return '7';
    }
  }
  switch (inv) {
    case 0: return '';
    case 1: return '6';
    case 2: return '6/4';
    default: return '';
  }
}

/**
 * Decide whether to add a seventh to a chord based on idiomatic tonal rules.
 *
 * @param deg - Scale degree (0-based: 0=I, 1=ii, etc.)
 * @param groupPcs - Soprano pitch classes in this harmonic slot.
 * @param seventhPc - The diatonic 7th PC for this degree.
 * @param isFirst - true if this is the first chord.
 * @param isLast - true if this is the last chord.
 * @param nextDeg - The degree of the next chord (-1 if unknown/last).
 * @param isMinor - true for minor key.
 * @returns true if a seventh should be added.
 */
function shouldUseSeventh(
  deg: number,
  groupPcs: number[],
  seventhPc: number,
  rootPc: number,
  isFirst: boolean,
  isLast: boolean,
  nextDeg: number,
  isMinor: boolean
): boolean {
  // Last chord: never add seventh (needs stability)
  if (isLast) return false;
  // First chord: only add seventh on V (dominant preparation rare but okay)
  if (isFirst && deg !== 4) return false;

  // V → always use seventh (V7 is the most idiomatic seventh chord)
  if (deg === 4) return true;

  // viio → use seventh (viio7 / viiø7) when not last
  if (deg === 6) return true;

  // ─── Primary motion rule ──────────────────────────────────────────
  // The 7th resolves naturally when the root moves by:
  //   • UP a 2nd  (interval +1 mod 7, e.g. IV→V, I→ii)
  //   • DOWN a 3rd (interval -2 mod 7 = +5, e.g. I→vi, V→iii)
  //   • UP a 4th  (interval +3 mod 7, e.g. ii→V, vi→ii, I→IV)
  // BUT only when the natural seventh is MINOR (10 semitones) or DIMINISHED (9).
  // Major sevenths (11 semi, e.g. Imaj7, IVmaj7) are not idiomatic in chorale style.
  if (nextDeg >= 0) {
    const interval = ((nextDeg - deg) % 7 + 7) % 7; // 0-6
    const isPrimaryMotion = interval === 1    // up a 2nd
                         || interval === 5    // down a 3rd (= up a 5th inv.)
                         || interval === 3;   // up a 4th
    if (isPrimaryMotion) {
      // Check the seventh's quality: minor=10, diminished=9, major=11
      const seventhInterval = ((seventhPc - rootPc) % 12 + 12) % 12;
      if (seventhInterval <= 10) return true; // minor (10) or diminished (9)
      // Major seventh (11) → skip
    }
  }

  // Specific named cases (kept for clarity, though mostly covered above):
  // ii → V (up 4th, already covered)
  // vi → ii or IV (up 3rd / down 3rd, already covered)

  // I, iii → NO automatic sevenths unless primary motion applies.
  // Imaj7, iiimaj7 are not idiomatic in chorale style.
  return false;
}

/**
 * Automatically choose a roman numeral progression that fits a given soprano melody.
 *
 * Algorithm:
 * 1. Build diatonic triad PC sets for all 7 degrees.
 * 2. For each melody note, find which degrees contain its PC.
 * 3. Score candidates using tonal preferences (I/IV/V bias, cadence patterns,
 *    avoidance of consecutive repetition, etc.).
 * 4. Return the best-scoring progression.
 *
 * @param melody  - Array of { midi, measure, beat } soprano constraint points.
 * @param tonic   - Key tonic (e.g. 'C', 'Bb').
 * @param isMinor - true for minor key.
 * @param harmonicRhythmBeats - Optional: how many beats each chord lasts.
 *        0 or undefined = one chord per melody note (default).
 *        e.g. 2 = one chord per half note, 4 = one per whole note.
 * @param beatsPerMeasure - Beats per measure (needed when harmonicRhythmBeats > 0). Default 4.
 * @returns Array of RomanChord entries matching the harmonic rhythm positions.
 */
export function autoHarmonize(
  melody: SopranoConstraint[],
  tonic: string,
  isMinor: boolean,
  harmonicRhythmBeats: number = 0,
  beatsPerMeasure: number = 4
): RomanChord[] {
  if (melody.length === 0) return [];

  const tonicPc = noteNameToPc(tonic);
  const scale = buildScale(tonic, isMinor);
  const naturalScale = isMinor ? buildNaturalMinorScale(tonic) : scale;
  const romanLabels = isMinor ? DIATONIC_ROMANS_MINOR : DIATONIC_ROMANS_MAJOR;

  // Build PC sets for each diatonic triad (using natural minor for III, VI, iv in minor)
  const triadPcSets: number[][] = [];
  // Also build seventh PCs for each degree
  const seventhPcs: number[] = [];
  for (let deg = 0; deg < 7; deg++) {
    const useScale = isMinor && (deg !== 4 && deg !== 6) ? naturalScale : scale;
    const root = useScale[deg];
    const third = useScale[(deg + 2) % 7];
    const fifth = useScale[(deg + 4) % 7];
    const seventh = useScale[(deg + 6) % 7];
    triadPcSets.push([
      (tonicPc + root.semiFromRoot) % 12,
      (tonicPc + third.semiFromRoot) % 12,
      (tonicPc + fifth.semiFromRoot) % 12,
    ]);
    seventhPcs.push((tonicPc + seventh.semiFromRoot) % 12);
  }

  // Tonal weights: prefer I, V, IV — penalize iii, viio
  const baseWeight: Record<number, number> = {
    0: 10,  // I
    1: 5,   // ii
    2: 2,   // iii
    3: 8,   // IV
    4: 9,   // V
    5: 6,   // vi
    6: 3,   // viio
  };

  const n = melody.length;
  const result: RomanChord[] = [];
  let prevDeg = -1;

  // ── Group melody notes by harmonic rhythm slots ─────────────────────
  type MelodyGroup = { pcs: number[]; measure: number; beat: number };
  let groups: MelodyGroup[];

  if (harmonicRhythmBeats > 0) {
    // Convert each melody point to an absolute beat position
    const absBeat = (m: SopranoConstraint) => m.measure * beatsPerMeasure + (m.beat - 1);

    // Build groups: each covers `harmonicRhythmBeats` beats
    const groupMap = new Map<number, MelodyGroup>();
    for (const m of melody) {
      const ab = absBeat(m);
      const slotIndex = Math.floor(ab / harmonicRhythmBeats);
      if (!groupMap.has(slotIndex)) {
        const slotAbsBeat = slotIndex * harmonicRhythmBeats;
        const slotMeasure = Math.floor(slotAbsBeat / beatsPerMeasure);
        const slotBeat = (slotAbsBeat % beatsPerMeasure) + 1;
        groupMap.set(slotIndex, { pcs: [], measure: slotMeasure, beat: slotBeat });
      }
      groupMap.get(slotIndex)!.pcs.push(((m.midi % 12) + 12) % 12);
    }
    groups = [...groupMap.values()];
  } else {
    // One group per melody note (original behavior)
    groups = melody.map(m => ({
      pcs: [((m.midi % 12) + 12) % 12],
      measure: m.measure,
      beat: m.beat,
    }));
  }

  const totalGroups = groups.length;
  let prevBassMidi = -1;  // Track previous bass for smooth voice leading

  for (let i = 0; i < totalGroups; i++) {
    const group = groups[i];
    const groupPcs = group.pcs;

    // Find candidate degrees whose triad covers the group's PCs
    const candidates: { deg: number; score: number; coverage: number }[] = [];
    for (let deg = 0; deg < 7; deg++) {
      const pcs = triadPcSets[deg];
      // Count how many of the group's PCs are in this triad
      const covered = groupPcs.filter(pc => pcs.includes(pc)).length;
      if (covered === 0) continue;

      let score = baseWeight[deg] ?? 1;

      // Coverage bonus: more melody notes covered = better fit
      score += (covered / groupPcs.length) * 5;

      // Bonus: if every melody PC in this group belongs to the chord
      if (covered === groupPcs.length) score += 3;

      // Penalty: same degree as previous chord → monotonous
      if (deg === prevDeg) score -= 4;

      // ─── Cadential patterns ───────────────────────────────────────
      // Last chord should be I (or i)
      if (i === totalGroups - 1 && deg === 0) score += 8;
      if (i === totalGroups - 1 && deg !== 0) score -= 5;

      // Penultimate → prefer V (authentic cadence) or IV (plagal)
      if (i === totalGroups - 2 && deg === 4) score += 6;
      if (i === totalGroups - 2 && deg === 3) score += 3;

      // V → I resolution bonus (if prev was V and current is I)
      if (prevDeg === 4 && deg === 0) score += 5;
      // IV → V progression bonus
      if (prevDeg === 3 && deg === 4) score += 3;
      // ii → V progression bonus
      if (prevDeg === 1 && deg === 4) score += 3;
      // vi → ii or IV bonus
      if (prevDeg === 5 && (deg === 1 || deg === 3)) score += 2;

      // First chord → prefer I strongly
      if (i === 0 && deg === 0) score += 5;

      candidates.push({ deg, score, coverage: covered });
    }

    // If no candidate found (non-diatonic soprano?), default to I
    if (candidates.length === 0) {
      const inv = chooseBestInversion(0, triadPcSets, tonicPc, prevBassMidi, i === 0, i === totalGroups - 1);
      result.push({
        roman: romanLabels[0] + inversionSuffix(inv, false),
        measure: group.measure,
        beat: group.beat,
        inversion: inv,
      });
      prevBassMidi = bassMidiForInversion(0, inv, triadPcSets, tonicPc);
      prevDeg = 0;
      continue;
    }

    // Pick highest score (break ties by coverage)
    candidates.sort((a, b) => b.score - a.score || b.coverage - a.coverage);
    const best = candidates[0];

    // ─── Seventh decision ─────────────────────────────────────────────
    // Quick lookahead: peek at the next group to estimate next degree
    let nextDeg = -1;
    if (i + 1 < totalGroups) {
      const nextGroupPcs = groups[i + 1].pcs;
      let bestNextScore = -Infinity;
      for (let d = 0; d < 7; d++) {
        const pcs = triadPcSets[d];
        const cov = nextGroupPcs.filter(pc => pcs.includes(pc)).length;
        if (cov === 0) continue;
        let sc = (baseWeight[d] ?? 1) + (cov / nextGroupPcs.length) * 5;
        if (d === best.deg) sc -= 4; // penalize same as current
        if (i + 1 === totalGroups - 1 && d === 0) sc += 8; // last chord = I
        if (sc > bestNextScore) { bestNextScore = sc; nextDeg = d; }
      }
    }

    const useSeventh = shouldUseSeventh(
      best.deg, groupPcs, seventhPcs[best.deg], triadPcSets[best.deg][0],
      i === 0, i === totalGroups - 1, nextDeg, isMinor
    );

    const maxInv = useSeventh ? 3 : 2;
    const inv = chooseBestInversion(best.deg, triadPcSets, tonicPc, prevBassMidi, i === 0, i === totalGroups - 1);
    // Clamp inversion to valid range for the chord type
    const clampedInv = Math.min(inv, maxInv);

    result.push({
      roman: romanLabels[best.deg] + inversionSuffix(clampedInv, useSeventh),
      measure: group.measure,
      beat: group.beat,
      inversion: clampedInv,
    });
    prevBassMidi = bassMidiForInversion(best.deg, clampedInv, triadPcSets, tonicPc);
    prevDeg = best.deg;
  }

  return result;
}

// ─── Auto-Harmonize From Bass ("Basso Dato") ──────────────────────────────

/**
 * Given a bass line (MIDI notes at specific measure/beat positions),
 * infer the most likely diatonic chord + inversion for each bass note.
 * Unlike autoHarmonize (which matches PCs against triads in general),
 * this function determines the chord based on the bass note's position
 * within each diatonic triad: root = inv 0, 3rd = inv 1, 5th = inv 2.
 */
export function autoHarmonizeFromBass(
  bassLine: SopranoConstraint[],
  tonic: string,
  isMinor: boolean,
  harmonicRhythmBeats: number = 0,
  beatsPerMeasure: number = 4
): RomanChord[] {
  if (bassLine.length === 0) return [];

  const tonicPc = noteNameToPc(tonic);
  const scale = buildScale(tonic, isMinor);
  const naturalScale = isMinor ? buildNaturalMinorScale(tonic) : scale;
  const romanLabels = isMinor ? DIATONIC_ROMANS_MINOR : DIATONIC_ROMANS_MAJOR;

  // Build PC sets for each diatonic triad
  const triadPcSets: number[][] = [];
  for (let deg = 0; deg < 7; deg++) {
    const useScale = isMinor && (deg !== 4 && deg !== 6) ? naturalScale : scale;
    const root = useScale[deg];
    const third = useScale[(deg + 2) % 7];
    const fifth = useScale[(deg + 4) % 7];
    triadPcSets.push([
      (tonicPc + root.semiFromRoot) % 12,
      (tonicPc + third.semiFromRoot) % 12,
      (tonicPc + fifth.semiFromRoot) % 12,
    ]);
  }

  // Tonal weights: prefer I, V, IV
  const baseWeight: Record<number, number> = {
    0: 10, 1: 5, 2: 2, 3: 8, 4: 9, 5: 6, 6: 3,
  };

  // Inversion preference: root position strongly preferred, 6/4 penalized
  const invWeight = [10, 6, -5]; // [root, 1st inv, 2nd inv (6/4)]

  // Group bass notes by harmonic rhythm
  type BassGroup = { pcs: number[]; measure: number; beat: number };
  let groups: BassGroup[];

  if (harmonicRhythmBeats > 0) {
    const absBeat = (m: SopranoConstraint) => m.measure * beatsPerMeasure + (m.beat - 1);
    const groupMap = new Map<number, BassGroup>();
    for (const m of bassLine) {
      const ab = absBeat(m);
      const slotIndex = Math.floor(ab / harmonicRhythmBeats);
      if (!groupMap.has(slotIndex)) {
        const slotAbsBeat = slotIndex * harmonicRhythmBeats;
        const slotMeasure = Math.floor(slotAbsBeat / beatsPerMeasure);
        const slotBeat = (slotAbsBeat % beatsPerMeasure) + 1;
        groupMap.set(slotIndex, { pcs: [], measure: slotMeasure, beat: slotBeat });
      }
      groupMap.get(slotIndex)!.pcs.push(m.midi % 12);
    }
    groups = [...groupMap.entries()].sort((a, b) => a[0] - b[0]).map(e => e[1]);
  } else {
    groups = bassLine.map(m => ({ pcs: [m.midi % 12], measure: m.measure, beat: m.beat }));
  }

  const result: RomanChord[] = [];
  let prevDeg = -1;
  const totalGroups = groups.length;

  for (let i = 0; i < totalGroups; i++) {
    const group = groups[i];
    // Use first (or most common) PC as the bass pitch class
    const bassPc = group.pcs[0];

    // Find all candidates: which degree has this PC as root/3rd/5th?
    type Candidate = { deg: number; inv: number; score: number };
    const candidates: Candidate[] = [];

    for (let deg = 0; deg < 7; deg++) {
      const pcs = triadPcSets[deg];
      let inv = -1;
      if (pcs[0] === bassPc) inv = 0; // root position
      else if (pcs[1] === bassPc) inv = 1; // 1st inversion
      else if (pcs[2] === bassPc) inv = 2; // 2nd inversion
      if (inv < 0) continue;

      let score = (baseWeight[deg] ?? 1) + (invWeight[inv] ?? 0);

      // Penalize repeating same degree
      if (deg === prevDeg) score -= 3;

      // Cadential bonuses
      if (i === totalGroups - 1 && deg === 0) score += 12; // end on I
      if (i === totalGroups - 2 && deg === 4) score += 8; // penultimate V
      // Penalize 6/4 except cadential I6/4 before V
      if (inv === 2) {
        if (deg === 0 && i + 1 < totalGroups) {
          // Check if next bass is V (dominant) — then cadential I6/4 is OK
          const nextPc = groups[i + 1].pcs[0];
          const dominantRoot = triadPcSets[4][0];
          if (nextPc === dominantRoot) score += 8; // cadential 6/4 bonus
        }
      }

      candidates.push({ deg, inv, score });
    }

    if (candidates.length === 0) {
      // Fallback: I root position
      result.push({ roman: romanLabels[0], measure: group.measure, beat: group.beat, inversion: 0 });
      prevDeg = 0;
      continue;
    }

    candidates.sort((a, b) => b.score - a.score);
    const best = candidates[0];

    result.push({
      roman: romanLabels[best.deg] + inversionSuffix(best.inv, false),
      measure: group.measure,
      beat: group.beat,
      inversion: best.inv,
    });
    prevDeg = best.deg;
  }

  return result;
}

// ─── Helpers ───────────────────────────────────────────────────────────────

/** Convert beat duration to a NoteDuration name. */
function beatsToDuration(beats: number): string {
  if (beats >= 4) return 'whole';
  if (beats >= 2) return 'half';
  if (beats >= 1) return 'quarter';
  if (beats >= 0.5) return 'eighth';
  if (beats >= 0.25) return 'sixteenth';
  return 'quarter';
}

/** Build a KeySignature from tonic + mode (mirrors getKeySignature from musicTheory). */
function buildKeySignature(tonic: string, isMinor: boolean): KeySignature {
  // Sharp keys: C G D A E B F#/Gb (count of sharps)
  const SHARP_KEYS: Record<string, number> = {
    C: 0, G: 1, D: 2, A: 3, E: 4, B: 5, 'F#': 6, 'C#': 7,
  };
  // Flat keys: F Bb Eb Ab Db Gb Cb (count of flats)
  const FLAT_KEYS: Record<string, number> = {
    F: 1, Bb: 2, Eb: 3, Ab: 4, Db: 5, Gb: 6, Cb: 7,
  };

  // Minor → find relative major
  let majorKey = tonic;
  if (isMinor) {
    const minorPc = noteNameToPc(tonic);
    const relMajorPc = (minorPc + 3) % 12;
    // Find the standard spelling
    const majorNames: Record<number, string> = {
      0: 'C', 1: 'Db', 2: 'D', 3: 'Eb', 4: 'E', 5: 'F',
      6: 'Gb', 7: 'G', 8: 'Ab', 9: 'A', 10: 'Bb', 11: 'B',
    };
    // Some minor keys use sharp majors
    const sharpMajors = new Set(['A', 'E', 'B', 'F#', 'C#', 'G#', 'D#']);
    if (sharpMajors.has(tonic)) {
      const sharpNames: Record<number, string> = {
        0: 'C', 1: 'C#', 2: 'D', 3: 'D#', 4: 'E', 5: 'F',
        6: 'F#', 7: 'G', 8: 'G#', 9: 'A', 10: 'A#', 11: 'B',
      };
      majorKey = sharpNames[relMajorPc] ?? majorNames[relMajorPc] ?? 'C';
    } else {
      majorKey = majorNames[relMajorPc] ?? 'C';
    }
  }

  if (SHARP_KEYS[majorKey] !== undefined) {
    return { type: 'sharp', count: SHARP_KEYS[majorKey] };
  }
  if (FLAT_KEYS[majorKey] !== undefined) {
    return { type: 'flat', count: FLAT_KEYS[majorKey] };
  }

  // Fallback: no accidentals
  return { type: 'sharp', count: 0 };
}
